<?php

namespace Database\Seeders;

use App\Models\DataModel;
use Illuminate\Database\Seeder;

class DataModelSeeder extends Seeder
{
    /**
     * Seed default data model definitions.
     */
    public function run(): void
    {
        DataModel::updateOrCreate(
            ['slug' => 'players'],
            [
                'model_name' => 'players',
                'description' => 'Default players data model schema.',
                'table_name' => 'players',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'BIGINT', 'required' => false],
                    'name' => ['type' => 'VARCHAR', 'required' => false],
                    'username' => ['type' => 'VARCHAR', 'required' => true],
                    'email' => ['type' => 'VARCHAR', 'required' => false],
                    'hp' => ['type' => 'VARCHAR', 'required' => false],
                    'bank' => ['type' => 'VARCHAR', 'required' => false],
                    'namarek' => ['type' => 'VARCHAR', 'required' => false],
                    'norek' => ['type' => 'VARCHAR', 'required' => false],
                    // 'password' => ['type' => 'VARCHAR', 'required' => false],
                    'banned_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'gamepage' => ['type' => 'VARCHAR', 'required' => false],
                    // 'lastbet' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'lastdeposit' => ['type' => 'VARCHAR', 'required' => false],
                    // 'is_first_deposit' => ['type' => 'TINYINT', 'required' => false],
                    // 'gametoken' => ['type' => 'VARCHAR', 'required' => false],
                    // 'lastip' => ['type' => 'VARCHAR', 'required' => false],
                    // 'status' => ['type' => 'VARCHAR', 'required' => false],
                    // 'referral' => ['type' => 'VARCHAR', 'required' => false],
                    // 'ref_update_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'agents_id' => ['type' => 'BIGINT', 'required' => false],
                    'agent' => ['type' => 'VARCHAR', 'required' => true, 'value' => config('services.agent.kode'),],
                    // 'language' => ['type' => 'VARCHAR', 'required' => false],
                    // 'playercode' => ['type' => 'VARCHAR', 'required' => false],
                    // 'balance' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'to' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'winloss' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    // 'playertoken' => ['type' => 'VARCHAR', 'required' => false],
                    // 'WDOTP' => ['type' => 'VARCHAR', 'required' => false],
                    'remark' => ['type' => 'TEXT', 'required' => false],
                    // 'lastlogin' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'lastactivity' => ['type' => 'TIMESTAMP', 'required' => false],
                    'targetTO' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'categoryTO' => ['type' => 'VARCHAR', 'required' => false],
                    // 'getbonustime' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'totalbonus' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    // 'flag' => ['type' => 'TINYINT', 'required' => false],
                    'startdateTO' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'useragent' => ['type' => 'TEXT', 'required' => false],
                    // 'fingerprint' => ['type' => 'VARCHAR', 'required' => false],
                    // 'browser' => ['type' => 'VARCHAR', 'required' => false],
                    // 'OS' => ['type' => 'VARCHAR', 'required' => false],
                    // 'device' => ['type' => 'VARCHAR', 'required' => false],
                    // 'devicefamily' => ['type' => 'VARCHAR', 'required' => false],
                    // 'referer' => ['type' => 'VARCHAR', 'required' => false],
                    // 'bonuswelcome_eventid' => ['type' => 'BIGINT', 'required' => false],
                    // 'bonuswelcome_valid' => ['type' => 'TINYINT', 'required' => false],
                    // 'freespin_balance_counter' => ['type' => 'INT', 'required' => false],
                    // 'remember_token' => ['type' => 'VARCHAR', 'required' => false],
                    // 'apk' => ['type' => 'TINYINT', 'required' => false],
                    // 'attention' => ['type' => 'TINYINT', 'required' => false],
                    // 'is_sync' => ['type' => 'INT', 'required' => false],
                    // 'request_id' => ['type' => 'VARCHAR', 'required' => false],
                    'created_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    'updated_at' => ['type' => 'TIMESTAMP', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'settings'],
            [
                'model_name' => 'Setting',
                'description' => 'Settings data model schema.',
                'table_name' => 'settings',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'kode' => ['type' => 'varchar(125)', 'required' => true],
                    'value' => ['type' => 'mediumtext', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'deposit'],
            [
                'model_name' => 'Deposit',
                'description' => 'Deposit data model schema.',
                'table_name' => 'deposits',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'invoice' => ['type' => 'varchar(125)', 'required' => false],
                    'order_id' => ['type' => 'varchar(125)', 'required' => false],
                    // 'rrn' => ['type' => 'varchar(125)', 'required' => false],
                    // 'transaction_id' => ['type' => 'varchar(125)', 'required' => false],
                    // 'token' => ['type' => 'varchar(125)', 'required' => false],
                    'payment_type' => ['type' => 'varchar(125)', 'required' => false],
                    'merchant_name' => ['type' => 'varchar(125)', 'required' => false],
                    'username' => ['type' => 'varchar(125)', 'required' => false],
                    'player_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'date' => ['type' => 'datetime', 'required' => false],
                    'saldoawal' => ['type' => 'decimal(14,3)', 'required' => false],
                    'depoamount' => ['type' => 'decimal(14,3)', 'required' => false],
                    'amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    'multiplier' => ['type' => 'int(11)', 'required' => false],
                    // 'bonus' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'quotabonusleft' => ['type' => 'decimal(14,3)', 'required' => false],
                    'total' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonus_type' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bonusrate' => ['type' => 'int(11)', 'required' => false],
                    // 'rate' => ['type' => 'int(11)', 'required' => false],
                    // 'fee_percentage' => ['type' => 'int(11)', 'required' => false],
                    // 'fee_amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusmisideposit_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusmisideposit_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusmisideposit_type' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bonusmisideposit_rate' => ['type' => 'int(11)', 'required' => false],
                    // 'bonusmisideposit_bonus' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusmisideposit_multiplier' => ['type' => 'int(11)', 'required' => false],
                    // 'bonusmisideposit_quota_left' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusfreespin_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusfreespin_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusajakteman_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusajakteman_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusberuntun_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusberuntun_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonus_deposit_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'berita' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'nama' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norek' => ['type' => 'varchar(125)', 'required' => false],
                    // 'jenisbank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'ip' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bankuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'namarekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'slip' => ['type' => 'varchar(125)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'operatorby' => ['type' => 'varchar(125)', 'required' => false],
                    'operatortime' => ['type' => 'datetime', 'required' => false],
                    'optime' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'operatorbymanual' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => "enum('waitpayment','new','accept','reject')", 'required' => false],
                    // 'referral' => ['type' => 'varchar(125)', 'required' => false],
                    // 'deposit_10x_id' => ['type' => 'int(11)', 'required' => false],
                    // 'isfirstdepositall' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'isfirstdepositdaily' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'file' => ['type' => 'varchar(125)', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    // 'response' => ['type' => 'text', 'required' => false],
                    // 'is_sync' => ['type' => 'int(11)', 'required' => false],
                    'request_id' => ['type' => 'varchar(125)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'withdraw'],
            [
                'model_name' => 'Withdraw',
                'description' => 'Withdraw data model schema.',
                'table_name' => 'withdraws',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'invoice' => ['type' => 'varchar(125)', 'required' => false],
                    'order_id' => ['type' => 'varchar(125)', 'required' => false],
                    'username' => ['type' => 'varchar(125)', 'required' => false],
                    'player_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'date' => ['type' => 'datetime', 'required' => false],
                    'saldoawal' => ['type' => 'decimal(14,3)', 'required' => false],
                    'amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'average_deposit' => ['type' => 'decimal(14,3)', 'required' => false],
                    'ratecharge' => ['type' => 'double(8,2)', 'required' => false],
                    'givenamount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'nama' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norek' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bankuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'namarekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'isfirstwd' => ['type' => 'tinyint(1)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    // 'ip' => ['type' => 'varchar(125)', 'required' => false],
                    'operatorby' => ['type' => 'varchar(125)', 'required' => false],
                    'operatortime' => ['type' => 'datetime', 'required' => false],
                    'operatorbymanual' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => "enum('new','accept','reject')", 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'sn' => ['type' => 'varchar(125)', 'required' => false],
                    // 'is_sync' => ['type' => 'int(11)', 'required' => false],
                    // 'request_id' => ['type' => 'varchar(125)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'promo'],
            [
                'model_name' => 'Promo',
                'description' => 'Promo data model schema.',
                'table_name' => 'promos',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'title' => ['type' => 'varchar(125)', 'required' => false],
                    'body' => ['type' => 'text', 'required' => false],
                    'image' => ['type' => 'varchar(125)', 'required' => false],
                    'start_date' => ['type' => 'datetime', 'required' => false],
                    'end_date' => ['type' => 'datetime', 'required' => false],
                    'slug' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => 'varchar(125)', 'required' => false],
                    'buttonlink' => ['type' => 'varchar(125)', 'required' => false],
                    'category' => ['type' => "enum('casino','sports')", 'required' => false],
                    'isbanner' => ['type' => 'tinyint(1)', 'required' => false],
                    'ispromotion' => ['type' => 'tinyint(1)', 'required' => false],
                    'urutan' => ['type' => 'int(11)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'language' => ['type' => 'varchar(125)', 'required' => true, 'value' => 'id'],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                    'deleted_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'game'],
            [
                'model_name' => 'Game',
                'description' => 'Game data model schema.',
                'table_name' => 'games',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'name' => ['type' => 'varchar(125)', 'required' => false],
                    'gameid' => ['type' => 'varchar(125)', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'category' => ['type' => 'varchar(125)', 'required' => false],
                    'iframe' => ['type' => 'tinyint(1)', 'required' => false],
                    'image' => ['type' => 'varchar(125)', 'required' => false],
                    'url' => ['type' => 'varchar(125)', 'required' => false],
                    'urutan' => ['type' => 'int(11)', 'required' => false],
                    'isshow' => ['type' => 'tinyint(1)', 'required' => false],
                    'isspecialto' => ['type' => 'tinyint(1)', 'required' => false],
                    'keyword' => ['type' => 'text', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'auto_bank_settings'],
            [
                'model_name' => 'AutoBankSetting',
                'description' => 'Auto bank settings data model schema.',
                'table_name' => 'auto_bank_settings',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'agent' => ['type' => 'varchar(125)', 'required' => false],
                    'bank' => ['type' => 'varchar(125)', 'required' => false],
                    'coin' => ['type' => 'varchar(125)', 'required' => false],
                    'nama' => ['type' => 'varchar(125)', 'required' => false],
                    'norek' => ['type' => 'varchar(125)', 'required' => false],
                    'jenis' => ['type' => 'varchar(125)', 'required' => false],
                    // 'rate' => ['type' => 'int(11)', 'required' => false],
                    // 'seq' => ['type' => 'int(11)', 'required' => false],
                    'active' => ['type' => 'tinyint(1)', 'required' => false],
                    'can_view' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_maintenance' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_deposit_bank' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_withdraw_bank' => ['type' => 'tinyint(1)', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'provider_name' => ['type' => 'varchar(125)', 'required' => false],
                    'provider_alias' => ['type' => 'varchar(125)', 'required' => false],
                    'merchant_name' => ['type' => 'varchar(125)', 'required' => false],
                    'min_deposit' => ['type' => 'int(11)', 'required' => false],
                    'max_deposit' => ['type' => 'int(11)', 'required' => false],
                    // 'amount_delimeter' => ['type' => 'varchar(125)', 'required' => false],
                    // 'message_html' => ['type' => 'text', 'required' => false],
                    'show_cancel' => ['type' => 'tinyint(1)', 'required' => false],
                    'type' => ['type' => 'varchar(125)', 'required' => false],
                    'order_url' => ['type' => 'varchar(125)', 'required' => false],
                    'cancel_url' => ['type' => 'varchar(125)', 'required' => false],
                    'callback_url' => ['type' => 'varchar(125)', 'required' => false],
                    'fee' => ['type' => 'double(8,2)', 'required' => false],
                    'charge' => ['type' => 'double(8,2)', 'required' => false],
                    'timeout_in_seconds' => ['type' => 'int(125)', 'required' => false],
                    'attempt_cancel' => ['type' => 'varchar(125)', 'required' => false],
                    'active_withdraw' => ['type' => 'tinyint(1)', 'required' => false],
                    'can_withdraw' => ['type' => 'tinyint(1)', 'required' => false],
                    'min_withdraw' => ['type' => 'int(11)', 'required' => false],
                    'max_withdraw' => ['type' => 'int(11)', 'required' => false],
                    'start_withdraw_amount' => ['type' => 'int(11)', 'required' => false],
                    'end_withdraw_amount' => ['type' => 'int(11)', 'required' => false],
                    'min_withdraw_count' => ['type' => 'int(11)', 'required' => false],
                    'flag_player' => ['type' => 'tinyint(1)', 'required' => false],
                    'multiple_merchant' => ['type' => 'varchar(125)', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'providers'],
            [
                'model_name' => 'Provider',
                'description' => 'Default providers data model schema.',
                'table_name' => 'providers',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id'       => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'name'     => ['type' => 'varchar(125)', 'required' => false],
                    'image'    => ['type' => 'varchar(125)', 'required' => false],
                    'slug'     => ['type' => 'varchar(125)', 'required' => false],
                    'alias'    => ['type' => 'varchar(125)', 'required' => false],
                    'active'   => ['type' => 'tinyint(1)', 'required' => false],
                    'category' => ['type' => "enum('casino','sports','e-sports')", 'required' => false],
                    'isshow'   => ['type' => 'tinyint(1)', 'required' => false],
                    'urutan'   => ['type' => 'int(11)', 'required' => false],
                    'timezone' => ['type' => 'varchar(50)', 'required' => false],
                ],
            ]
        );
    }
}
