<?php

namespace Database\Seeders;

use App\Models\DataModel;
use Illuminate\Database\Seeder;

class DataModelSeeder extends Seeder
{
    /**
     * Seed default data model definitions.
     */
    public function run(): void
    {
        DataModel::updateOrCreate(
            ['slug' => 'players'],
            [
                'model_name' => 'players',
                'description' => 'Default players data model schema.',
                'table_name' => 'players',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'BIGINT', 'required' => false],
                    'name' => ['type' => 'VARCHAR', 'required' => false],
                    'username' => ['type' => 'VARCHAR', 'required' => true],
                    'email' => ['type' => 'VARCHAR', 'required' => false],
                    'hp' => ['type' => 'VARCHAR', 'required' => false],
                    'bank' => ['type' => 'VARCHAR', 'required' => false],
                    'namarek' => ['type' => 'VARCHAR', 'required' => false],
                    'norek' => ['type' => 'VARCHAR', 'required' => false],
                    // 'password' => ['type' => 'VARCHAR', 'required' => false],
                    'banned_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'gamepage' => ['type' => 'VARCHAR', 'required' => false],
                    // 'lastbet' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'lastdeposit' => ['type' => 'VARCHAR', 'required' => false],
                    // 'is_first_deposit' => ['type' => 'TINYINT', 'required' => false],
                    // 'gametoken' => ['type' => 'VARCHAR', 'required' => false],
                    // 'lastip' => ['type' => 'VARCHAR', 'required' => false],
                    // 'status' => ['type' => 'VARCHAR', 'required' => false],
                    // 'referral' => ['type' => 'VARCHAR', 'required' => false],
                    // 'ref_update_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'agents_id' => ['type' => 'BIGINT', 'required' => false],
                    'agent' => ['type' => 'VARCHAR', 'required' => true, 'value' => config('services.agent.kode'),],
                    // 'language' => ['type' => 'VARCHAR', 'required' => false],
                    // 'playercode' => ['type' => 'VARCHAR', 'required' => false],
                    // 'balance' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'to' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'winloss' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    // 'playertoken' => ['type' => 'VARCHAR', 'required' => false],
                    // 'WDOTP' => ['type' => 'VARCHAR', 'required' => false],
                    'remark' => ['type' => 'TEXT', 'required' => false],
                    // 'lastlogin' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'lastactivity' => ['type' => 'TIMESTAMP', 'required' => false],
                    'targetTO' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    'categoryTO' => ['type' => 'VARCHAR', 'required' => false],
                    // 'getbonustime' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'totalbonus' => ['type' => 'DECIMAL(14,3)', 'required' => false],
                    // 'flag' => ['type' => 'TINYINT', 'required' => false],
                    'startdateTO' => ['type' => 'TIMESTAMP', 'required' => false],
                    // 'useragent' => ['type' => 'TEXT', 'required' => false],
                    // 'fingerprint' => ['type' => 'VARCHAR', 'required' => false],
                    // 'browser' => ['type' => 'VARCHAR', 'required' => false],
                    // 'OS' => ['type' => 'VARCHAR', 'required' => false],
                    // 'device' => ['type' => 'VARCHAR', 'required' => false],
                    // 'devicefamily' => ['type' => 'VARCHAR', 'required' => false],
                    // 'referer' => ['type' => 'VARCHAR', 'required' => false],
                    // 'bonuswelcome_eventid' => ['type' => 'BIGINT', 'required' => false],
                    // 'bonuswelcome_valid' => ['type' => 'TINYINT', 'required' => false],
                    // 'freespin_balance_counter' => ['type' => 'INT', 'required' => false],
                    // 'remember_token' => ['type' => 'VARCHAR', 'required' => false],
                    // 'apk' => ['type' => 'TINYINT', 'required' => false],
                    // 'attention' => ['type' => 'TINYINT', 'required' => false],
                    // 'is_sync' => ['type' => 'INT', 'required' => false],
                    // 'request_id' => ['type' => 'VARCHAR', 'required' => false],
                    'created_at' => ['type' => 'TIMESTAMP', 'required' => false],
                    'updated_at' => ['type' => 'TIMESTAMP', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'settings'],
            [
                'model_name' => 'Setting',
                'description' => 'Settings data model schema.',
                'table_name' => 'settings',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'kode' => ['type' => 'varchar(125)', 'required' => true],
                    'value' => ['type' => 'mediumtext', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'deposit'],
            [
                'model_name' => 'Deposit',
                'description' => 'Deposit data model schema.',
                'table_name' => 'deposits',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'invoice' => ['type' => 'varchar(125)', 'required' => false],
                    'order_id' => ['type' => 'varchar(125)', 'required' => false],
                    // 'rrn' => ['type' => 'varchar(125)', 'required' => false],
                    // 'transaction_id' => ['type' => 'varchar(125)', 'required' => false],
                    // 'token' => ['type' => 'varchar(125)', 'required' => false],
                    'payment_type' => ['type' => 'varchar(125)', 'required' => false],
                    'merchant_name' => ['type' => 'varchar(125)', 'required' => false],
                    'username' => ['type' => 'varchar(125)', 'required' => false],
                    'player_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'date' => ['type' => 'datetime', 'required' => false],
                    'saldoawal' => ['type' => 'decimal(14,3)', 'required' => false],
                    'depoamount' => ['type' => 'decimal(14,3)', 'required' => false],
                    'amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    'multiplier' => ['type' => 'int(11)', 'required' => false],
                    // 'bonus' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'quotabonusleft' => ['type' => 'decimal(14,3)', 'required' => false],
                    'total' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonus_type' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bonusrate' => ['type' => 'int(11)', 'required' => false],
                    // 'rate' => ['type' => 'int(11)', 'required' => false],
                    // 'fee_percentage' => ['type' => 'int(11)', 'required' => false],
                    // 'fee_amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusmisideposit_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusmisideposit_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusmisideposit_type' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bonusmisideposit_rate' => ['type' => 'int(11)', 'required' => false],
                    // 'bonusmisideposit_bonus' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusmisideposit_multiplier' => ['type' => 'int(11)', 'required' => false],
                    // 'bonusmisideposit_quota_left' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bonusfreespin_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusfreespin_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusajakteman_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusajakteman_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonusberuntun_eventid' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    // 'bonusberuntun_valid' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'bonus_deposit_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'berita' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'nama' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norek' => ['type' => 'varchar(125)', 'required' => false],
                    // 'jenisbank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'ip' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bankuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'namarekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'slip' => ['type' => 'varchar(125)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'operatorby' => ['type' => 'varchar(125)', 'required' => false],
                    'operatortime' => ['type' => 'datetime', 'required' => false],
                    'optime' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'operatorbymanual' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => "enum('waitpayment','new','accept','reject')", 'required' => false],
                    // 'referral' => ['type' => 'varchar(125)', 'required' => false],
                    // 'deposit_10x_id' => ['type' => 'int(11)', 'required' => false],
                    // 'isfirstdepositall' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'isfirstdepositdaily' => ['type' => 'tinyint(1)', 'required' => false],
                    // 'file' => ['type' => 'varchar(125)', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    // 'response' => ['type' => 'text', 'required' => false],
                    // 'is_sync' => ['type' => 'int(11)', 'required' => false],
                    'request_id' => ['type' => 'varchar(125)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'withdraw'],
            [
                'model_name' => 'Withdraw',
                'description' => 'Withdraw data model schema.',
                'table_name' => 'withdraws',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'invoice' => ['type' => 'varchar(125)', 'required' => false],
                    'order_id' => ['type' => 'varchar(125)', 'required' => false],
                    'username' => ['type' => 'varchar(125)', 'required' => false],
                    'player_id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'date' => ['type' => 'datetime', 'required' => false],
                    'saldoawal' => ['type' => 'decimal(14,3)', 'required' => false],
                    'amount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'average_deposit' => ['type' => 'decimal(14,3)', 'required' => false],
                    'ratecharge' => ['type' => 'double(8,2)', 'required' => false],
                    'givenamount' => ['type' => 'decimal(14,3)', 'required' => false],
                    // 'bank' => ['type' => 'varchar(125)', 'required' => false],
                    // 'nama' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norek' => ['type' => 'varchar(125)', 'required' => false],
                    // 'bankuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'norekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'namarekuser' => ['type' => 'varchar(125)', 'required' => false],
                    // 'isfirstwd' => ['type' => 'tinyint(1)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    // 'ip' => ['type' => 'varchar(125)', 'required' => false],
                    'operatorby' => ['type' => 'varchar(125)', 'required' => false],
                    'operatortime' => ['type' => 'datetime', 'required' => false],
                    'operatorbymanual' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => "enum('new','accept','reject')", 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'sn' => ['type' => 'varchar(125)', 'required' => false],
                    // 'is_sync' => ['type' => 'int(11)', 'required' => false],
                    // 'request_id' => ['type' => 'varchar(125)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'promo'],
            [
                'model_name' => 'Promo',
                'description' => 'Promo data model schema.',
                'table_name' => 'promos',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'title' => ['type' => 'varchar(125)', 'required' => false],
                    'body' => ['type' => 'text', 'required' => false],
                    'image' => ['type' => 'varchar(125)', 'required' => false],
                    'start_date' => ['type' => 'datetime', 'required' => false],
                    'end_date' => ['type' => 'datetime', 'required' => false],
                    'slug' => ['type' => 'varchar(125)', 'required' => false],
                    'status' => ['type' => 'varchar(125)', 'required' => false],
                    'buttonlink' => ['type' => 'varchar(125)', 'required' => false],
                    'category' => ['type' => "enum('casino','sports')", 'required' => false],
                    'isbanner' => ['type' => 'tinyint(1)', 'required' => false],
                    'ispromotion' => ['type' => 'tinyint(1)', 'required' => false],
                    'urutan' => ['type' => 'int(11)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode'),],
                    'language' => ['type' => 'varchar(125)', 'required' => true, 'value' => 'id'],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                    'deleted_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'event-bonus'],
            [
                'model_name' => 'EventBonus',
                'description' => 'Event bonus data model schema.',
                'table_name' => 'event_bonuses',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'bonus_type' => ['type' => 'varchar', 'required' => false],
                    'status' => ['type' => 'varchar', 'required' => true , 'value' => 'Active'],
                    'agent' => ['type' => 'varchar', 'required' => true, 'value' => config('services.agent.kode')],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'game'],
            [
                'model_name' => 'Game',
                'description' => 'Game data model schema.',
                'table_name' => 'games',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'name' => ['type' => 'varchar(125)', 'required' => false],
                    'gameid' => ['type' => 'varchar(125)', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'category' => ['type' => 'varchar(125)', 'required' => false],
                    'iframe' => ['type' => 'tinyint(1)', 'required' => false],
                    'image' => ['type' => 'varchar(125)', 'required' => false],
                    'url' => ['type' => 'varchar(125)', 'required' => false],
                    'urutan' => ['type' => 'int(11)', 'required' => false],
                    'isshow' => ['type' => 'tinyint(1)', 'required' => false],
                    'isspecialto' => ['type' => 'tinyint(1)', 'required' => false],
                    'keyword' => ['type' => 'text', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'auto_bank_settings'],
            [
                'model_name' => 'AutoBankSetting',
                'description' => 'Auto bank settings data model schema.',
                'table_name' => 'auto_bank_settings',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'agent' => ['type' => 'varchar(125)', 'required' => false],
                    'bank' => ['type' => 'varchar(125)', 'required' => false],
                    'coin' => ['type' => 'varchar(125)', 'required' => false],
                    'nama' => ['type' => 'varchar(125)', 'required' => false],
                    'norek' => ['type' => 'varchar(125)', 'required' => false],
                    'jenis' => ['type' => 'varchar(125)', 'required' => false],
                    // 'rate' => ['type' => 'int(11)', 'required' => false],
                    // 'seq' => ['type' => 'int(11)', 'required' => false],
                    'active' => ['type' => 'tinyint(1)', 'required' => false],
                    'can_view' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_maintenance' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_deposit_bank' => ['type' => 'tinyint(1)', 'required' => false],
                    'is_withdraw_bank' => ['type' => 'tinyint(1)', 'required' => false],
                    'provider' => ['type' => 'varchar(125)', 'required' => false],
                    'provider_name' => ['type' => 'varchar(125)', 'required' => false],
                    'provider_alias' => ['type' => 'varchar(125)', 'required' => false],
                    'merchant_name' => ['type' => 'varchar(125)', 'required' => false],
                    'min_deposit' => ['type' => 'int(11)', 'required' => false],
                    'max_deposit' => ['type' => 'int(11)', 'required' => false],
                    // 'amount_delimeter' => ['type' => 'varchar(125)', 'required' => false],
                    // 'message_html' => ['type' => 'text', 'required' => false],
                    'show_cancel' => ['type' => 'tinyint(1)', 'required' => false],
                    'type' => ['type' => 'varchar(125)', 'required' => false],
                    'order_url' => ['type' => 'varchar(125)', 'required' => false],
                    'cancel_url' => ['type' => 'varchar(125)', 'required' => false],
                    'callback_url' => ['type' => 'varchar(125)', 'required' => false],
                    'fee' => ['type' => 'double(8,2)', 'required' => false],
                    'charge' => ['type' => 'double(8,2)', 'required' => false],
                    'timeout_in_seconds' => ['type' => 'int(125)', 'required' => false],
                    'attempt_cancel' => ['type' => 'varchar(125)', 'required' => false],
                    'active_withdraw' => ['type' => 'tinyint(1)', 'required' => false],
                    'can_withdraw' => ['type' => 'tinyint(1)', 'required' => false],
                    'min_withdraw' => ['type' => 'int(11)', 'required' => false],
                    'max_withdraw' => ['type' => 'int(11)', 'required' => false],
                    'start_withdraw_amount' => ['type' => 'int(11)', 'required' => false],
                    'end_withdraw_amount' => ['type' => 'int(11)', 'required' => false],
                    'min_withdraw_count' => ['type' => 'int(11)', 'required' => false],
                    'flag_player' => ['type' => 'tinyint(1)', 'required' => false],
                    'multiple_merchant' => ['type' => 'varchar(125)', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'rekenings'],
            [
                'model_name' => 'Rekening',
                'description' => 'Rekening (bank account) data model schema.',
                'table_name' => 'rekenings',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id'               => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'agents_id'        => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'agent'            => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode')],
                    'bank'             => ['type' => 'varchar(125)', 'required' => false],
                    'nama'             => ['type' => 'varchar(125)', 'required' => false],
                    'norek'            => ['type' => 'varchar(125)', 'required' => false],
                    'jenis'            => ['type' => 'varchar(125)', 'required' => false],
                    'rate'             => ['type' => 'int(11)', 'required' => false],
                    'seq'              => ['type' => 'int(11)', 'required' => false],
                    'logo'             => ['type' => 'varchar(125)', 'required' => false],
                    'isimage'          => ['type' => 'tinyint(1)', 'required' => false],
                    'qrcode'           => ['type' => 'varchar(125)', 'required' => false],
                    'active'           => ['type' => 'varchar(125)', 'required' => false],
                    'online'           => ['type' => 'varchar(125)', 'required' => false],
                    'jam_buka'         => ['type' => 'time', 'required' => false],
                    'jam_tutup'        => ['type' => 'time', 'required' => false],
                    'is_deposit_bank'  => ['type' => 'tinyint(1)', 'required' => false],
                    'is_withdraw_bank' => ['type' => 'tinyint(1)', 'required' => false],
                    'provider'         => ['type' => 'varchar(125)', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'providers'],
            [
                'model_name' => 'Provider',
                'description' => 'Default providers data model schema.',
                'table_name' => 'providers',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id'       => ['type' => 'bigint(20) UNSIGNED', 'required' => false],
                    'name'     => ['type' => 'varchar(125)', 'required' => false],
                    'image'    => ['type' => 'varchar(125)', 'required' => false],
                    'slug'     => ['type' => 'varchar(125)', 'required' => false],
                    'alias'    => ['type' => 'varchar(125)', 'required' => false],
                    'active'   => ['type' => 'tinyint(1)', 'required' => false],
                    'category' => ['type' => "enum('casino','sports','e-sports')", 'required' => false],
                    'isshow'   => ['type' => 'tinyint(1)', 'required' => false],
                    'urutan'   => ['type' => 'int(11)', 'required' => false],
                    'timezone' => ['type' => 'varchar(50)', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'agent-domains'],
            [
                'model_name' => 'AgentDomain',
                'description' => 'Agent domain data model schema.',
                'table_name' => 'agent_domains',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint unsigned', 'required' => false],
                    'domain' => ['type' => 'varchar(125)', 'required' => false],
                    'headertag' => ['type' => 'tinyint(1)', 'required' => false],
                    'noindex' => ['type' => 'tinyint(1)', 'required' => false],
                    'isapk' => ['type' => 'tinyint(1)', 'required' => false],
                    'ispromo' => ['type' => 'tinyint(1)', 'required' => false],
                    'issubdomain' => ['type' => 'tinyint(1)', 'required' => false],
                    'subdomain' => ['type' => 'varchar(125)', 'required' => false],
                    'agent' => ['type' => 'varchar(125)', 'required' => true, 'value' => config('services.agent.kode')],
                    'utama' => ['type' => "enum('on','off')", 'required' => false],
                    'zone_id' => ['type' => 'text', 'required' => false],
                    'cloudflare_api_key' => ['type' => 'varchar(125)', 'required' => false],
                    'cloudflare_email' => ['type' => 'varchar(125)', 'required' => false],
                    'cloudflare_account_id' => ['type' => 'varchar(125)', 'required' => false],
                    'IP' => ['type' => 'varchar(125)', 'required' => false],
                    'isDNS' => ['type' => 'tinyint(1)', 'required' => false],
                    'isSSL' => ['type' => 'tinyint(1)', 'required' => false],
                    'isIPv6' => ['type' => 'tinyint(1)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'bonus-apk'],
            [
                'model_name' => 'BonusAPK',
                'description' => 'Bonus APK log data model schema.',
                'table_name' => 'log_bonus_apks',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'gtx' => ['type' => 'varchar', 'required' => false],
                    'eventbonus_id' => ['type' => 'bigint', 'required' => false],
                    'player_id' => ['type' => 'bigint', 'required' => false],
                    'player' => ['type' => 'varchar', 'required' => false],
                    'agent' => ['type' => 'varchar', 'required' => true, 'value' => config('services.agent.kode')],
                    'amount' => ['type' => 'decimal', 'required' => false],
                    'multiplierTO' => ['type' => 'varchar', 'required' => false],
                    'depositcount' => ['type' => 'varchar', 'required' => false],
                    'status' => ['type' => 'enum', 'required' => false],
                    'is_read' => ['type' => 'tinyint', 'required' => false],
                    'surrender_bonus' => ['type' => 'varchar', 'required' => false],
                    'gtx_surrender' => ['type' => 'varchar', 'required' => false],
                    'gtx_done' => ['type' => 'varchar', 'required' => false],
                    'startdate' => ['type' => 'datetime', 'required' => false],
                    'enddate' => ['type' => 'datetime', 'required' => false],
                    'keterangan' => ['type' => 'text', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'expired_at' => ['type' => 'datetime', 'required' => false],
                    'claimed_at' => ['type' => 'datetime', 'required' => false],
                    'accepted_at' => ['type' => 'datetime', 'required' => false],
                    'reject_at' => ['type' => 'datetime', 'required' => false],
                    'stoppend_at' => ['type' => 'datetime', 'required' => false],
                    'cancelled_at' => ['type' => 'datetime', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'bonus-beruntun'],
            [
                'model_name' => 'BonusBeruntun',
                'description' => 'Bonus Deposit Beruntun (Daily Streak) log data model schema.',
                'table_name' => 'log_bonus_deposit10xes',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'gtx' => ['type' => 'varchar', 'required' => false],
                    'eventbonus_id' => ['type' => 'bigint', 'required' => false],
                    'player_id' => ['type' => 'bigint', 'required' => false],
                    'player' => ['type' => 'varchar', 'required' => false],
                    'agent' => ['type' => 'varchar', 'required' => false],
                    'amount' => ['type' => 'decimal', 'required' => false],
                    'multiplierTO' => ['type' => 'varchar', 'required' => false],
                    'depositcount' => ['type' => 'varchar', 'required' => false],
                    'status' => ['type' => 'enum', 'required' => false],
                    'is_read' => ['type' => 'tinyint', 'required' => false],
                    'surrender_bonus' => ['type' => 'varchar', 'required' => false],
                    'gtx_surrender' => ['type' => 'varchar', 'required' => false],
                    'gtx_done' => ['type' => 'varchar', 'required' => false],
                    'startdate' => ['type' => 'datetime', 'required' => false],
                    'enddate' => ['type' => 'datetime', 'required' => false],
                    'keterangan' => ['type' => 'text', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'expired_at' => ['type' => 'datetime', 'required' => false],
                    'claimed_at' => ['type' => 'datetime', 'required' => false],
                    'accepted_at' => ['type' => 'datetime', 'required' => false],
                    'reject_at' => ['type' => 'datetime', 'required' => false],
                    'stoppend_at' => ['type' => 'datetime', 'required' => false],
                    'cancelled_at' => ['type' => 'datetime', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'bonus-deposit'],
            [
                'model_name' => 'BonusDeposit',
                'description' => 'Bonus Deposit log data model schema.',
                'table_name' => 'log_bonus_misi_deposit_alls',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'gtx' => ['type' => 'varchar', 'required' => false],
                    'eventbonus_id' => ['type' => 'bigint', 'required' => false],
                    'deposit_id' => ['type' => 'varchar', 'required' => false],
                    'deposit_invoice' => ['type' => 'varchar', 'required' => false],
                    'depositall_type' => ['type' => 'varchar', 'required' => false],
                    'givenamount' => ['type' => 'decimal', 'required' => false],
                    'rate' => ['type' => 'int', 'required' => false],
                    'multiplierTO' => ['type' => 'int', 'required' => false],
                    'bonusamount' => ['type' => 'decimal', 'required' => false],
                    'player_id' => ['type' => 'bigint', 'required' => false],
                    'player' => ['type' => 'varchar', 'required' => false],
                    'agent' => ['type' => 'varchar', 'required' => false],
                    'first_deposit_bank_minamount' => ['type' => 'decimal', 'required' => false],
                    'first_deposit_bank_rate' => ['type' => 'int', 'required' => false],
                    'first_deposit_bank_maxbonus' => ['type' => 'decimal', 'required' => false],
                    'first_deposit_bank_multiplier' => ['type' => 'int', 'required' => false],
                    'first_deposit_bank_description' => ['type' => 'varchar', 'required' => false],
                    'daily_first_deposit_bank_minamount' => ['type' => 'decimal', 'required' => false],
                    'daily_first_deposit_bank_rate' => ['type' => 'int', 'required' => false],
                    'daily_first_deposit_bank_maxbonus' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_bank_minamount' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_bank_rate' => ['type' => 'int', 'required' => false],
                    'daily_deposit_bank_quota' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_bank_multiplier' => ['type' => 'int', 'required' => false],
                    'daily_deposit_bank_description' => ['type' => 'varchar', 'required' => false],
                    'first_deposit_nonbank_minamount' => ['type' => 'decimal', 'required' => false],
                    'first_deposit_nonbank_rate' => ['type' => 'int', 'required' => false],
                    'first_deposit_nonbank_maxbonus' => ['type' => 'decimal', 'required' => false],
                    'first_deposit_nonbank_multiplier' => ['type' => 'int', 'required' => false],
                    'first_deposit_nonbank_description' => ['type' => 'varchar', 'required' => false],
                    'daily_first_deposit_nonbank_minamount' => ['type' => 'decimal', 'required' => false],
                    'daily_first_deposit_nonbank_rate' => ['type' => 'int', 'required' => false],
                    'daily_first_deposit_nonbank_maxbonus' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_nonbank_minamount' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_nonbank_rate' => ['type' => 'int', 'required' => false],
                    'daily_deposit_nonbank_quota' => ['type' => 'decimal', 'required' => false],
                    'daily_deposit_nonbank_multiplier' => ['type' => 'int', 'required' => false],
                    'daily_deposit_nonbank_description' => ['type' => 'varchar', 'required' => false],
                    'jenisbank' => ['type' => 'varchar', 'required' => false],
                    'daily_deposit_quota_bonus_left' => ['type' => 'decimal', 'required' => false],
                    'autoaccept' => ['type' => 'tinyint', 'required' => false],
                    'status' => ['type' => 'enum', 'required' => false],
                    'is_read' => ['type' => 'tinyint', 'required' => false],
                    'surrender_bonus' => ['type' => 'varchar', 'required' => false],
                    'gtx_surrender' => ['type' => 'varchar', 'required' => false],
                    'gtx_done' => ['type' => 'varchar', 'required' => false],
                    'keterangan' => ['type' => 'text', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'expired_at' => ['type' => 'datetime', 'required' => false],
                    'claimed_at' => ['type' => 'datetime', 'required' => false],
                    'accepted_at' => ['type' => 'datetime', 'required' => false],
                    'reject_at' => ['type' => 'datetime', 'required' => false],
                    'stopped_at' => ['type' => 'datetime', 'required' => false],
                    'cancelled_at' => ['type' => 'datetime', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'bonus-ajak-teman'],
            [
                'model_name' => 'BonusAjakTeman',
                'description' => 'Bonus Ajak Teman (Referral Bonus) log data model schema.',
                'table_name' => 'log_bonus_referrals',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'gtx' => ['type' => 'varchar', 'required' => false],
                    'eventbonus_id' => ['type' => 'bigint', 'required' => false],
                    'referral_id' => ['type' => 'varchar', 'required' => false],
                    'player_id' => ['type' => 'bigint', 'required' => false],
                    'player' => ['type' => 'varchar', 'required' => false],
                    'by_user_id' => ['type' => 'bigint', 'required' => false],
                    'by_username' => ['type' => 'varchar', 'required' => false],
                    'deposit_id' => ['type' => 'bigint', 'required' => false],
                    'deposit_invoice' => ['type' => 'varchar', 'required' => false],
                    'status' => ['type' => 'enum', 'required' => false],
                    'is_read' => ['type' => 'tinyint', 'required' => false],
                    'surrender_bonus' => ['type' => 'varchar', 'required' => false],
                    'gtx_surrender' => ['type' => 'varchar', 'required' => false],
                    'gtx_done' => ['type' => 'varchar', 'required' => false],
                    'multiplierTO' => ['type' => 'int', 'required' => false],
                    'descriptionTO' => ['type' => 'varchar', 'required' => false],
                    'bonus_amount' => ['type' => 'decimal', 'required' => false],
                    'depositamount' => ['type' => 'decimal', 'required' => false],
                    'minamount' => ['type' => 'decimal', 'required' => false],
                    'fromamount' => ['type' => 'decimal', 'required' => false],
                    'toamount' => ['type' => 'decimal', 'required' => false],
                    'betweenbonus' => ['type' => 'decimal', 'required' => false],
                    'greaterbonus' => ['type' => 'decimal', 'required' => false],
                    'includenonbank' => ['type' => 'tinyint', 'required' => false],
                    'isfirstdeposit' => ['type' => 'tinyint', 'required' => false],
                    'autoaccept' => ['type' => 'tinyint', 'required' => false],
                    'expired_at' => ['type' => 'datetime', 'required' => false],
                    'claimed_at' => ['type' => 'datetime', 'required' => false],
                    'accepted_at' => ['type' => 'datetime', 'required' => false],
                    'reject_at' => ['type' => 'datetime', 'required' => false],
                    'stopped_at' => ['type' => 'datetime', 'required' => false],
                    'cancelled_at' => ['type' => 'datetime', 'required' => false],
                    'agent' => ['type' => 'varchar', 'required' => false],
                    'keterangan' => ['type' => 'text', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'bonus-voucher'],
            [
                'model_name' => 'BonusVoucher',
                'description' => 'Bonus Voucher log data model schema.',
                'table_name' => 'log_bonus_vouchers',
                'connection_name' => 'mysqlgame',
                'fields' => [
                    'id' => ['type' => 'bigint', 'required' => false],
                    'gtx' => ['type' => 'varchar', 'required' => false],
                    'eventbonus_id' => ['type' => 'bigint', 'required' => false],
                    'batch_id' => ['type' => 'bigint', 'required' => false],
                    'voucher_code' => ['type' => 'varchar', 'required' => false],
                    'amount' => ['type' => 'decimal', 'required' => false],
                    'multiplierTO' => ['type' => 'int', 'required' => false],
                    'status' => ['type' => 'varchar', 'required' => false],
                    'surrender_bonus' => ['type' => 'varchar', 'required' => false],
                    'gtx_surrender' => ['type' => 'varchar', 'required' => false],
                    'gtx_done' => ['type' => 'varchar', 'required' => false],
                    'player_id' => ['type' => 'bigint', 'required' => false],
                    'player' => ['type' => 'varchar', 'required' => false],
                    'agent_id' => ['type' => 'bigint', 'required' => false],
                    'agent' => ['type' => 'varchar', 'required' => false],
                    'keterangan' => ['type' => 'text', 'required' => false],
                    'remark' => ['type' => 'text', 'required' => false],
                    'claimed_at' => ['type' => 'datetime', 'required' => false],
                    'expired_at' => ['type' => 'datetime', 'required' => false],
                    'accepted_at' => ['type' => 'datetime', 'required' => false],
                    'reject_at' => ['type' => 'datetime', 'required' => false],
                    'stopped_at' => ['type' => 'datetime', 'required' => false],
                    'cancelled_at' => ['type' => 'datetime', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );

        DataModel::updateOrCreate(
            ['slug' => 'pools-periode'],
            [
                'model_name' => 'PoolsPeriode',
                'description' => 'Pools periode data model schema (lottery pool schedule & results).',
                'table_name'  => 'pools_has_periodes',
                'connection_name' => 'pgsqlgame',
                'fields' => [
                    'id'         => ['type' => 'bigint', 'required' => false],
                    'pools_id'   => ['type' => 'bigint', 'required' => false],
                    'date'       => ['type' => 'date', 'required' => false],
                    'days'       => ['type' => 'varchar(255)', 'required' => false],
                    'times'      => ['type' => 'varchar(255)', 'required' => false],
                    'datetimes'  => ['type' => 'varchar(255)', 'required' => false],
                    'opendt'     => ['type' => 'varchar(255)', 'required' => false],
                    'closedt'    => ['type' => 'varchar(255)', 'required' => false],
                    'resultdt'   => ['type' => 'varchar(255)', 'required' => false],
                    'periode'    => ['type' => 'bigint', 'required' => false],
                    'result1'    => ['type' => 'varchar(255)', 'required' => false],
                    'result2'    => ['type' => 'varchar(255)', 'required' => false],
                    'result3'    => ['type' => 'varchar(255)', 'required' => false],
                    'agent'      => ['type' => 'varchar(255)', 'required' => false],
                    'status'     => ['type' => 'varchar(255)', 'required' => false],
                    'created_at' => ['type' => 'timestamp', 'required' => false],
                    'updated_at' => ['type' => 'timestamp', 'required' => false],
                ],
            ]
        );
    }
}
