<?php

namespace Database\Seeders;

use App\Models\DataModel;
use App\Models\SystemConfig;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class SystemConfigSeeder extends Seeder
{
    /**
     * Seed default system config entries.
     */
    public function run(): void
    {
        $settingsDataModelId = DataModel::query()
            ->where('slug', 'settings')
            ->value('id');

        $agentDomainsDataModelId = DataModel::query()
            ->where('slug', 'agent-domains')
            ->value('id');

        if ($settingsDataModelId === null) {
            return;
        }

        $hasLookupRules = Schema::hasColumn('system_configs', 'lookup_rules');
        $hasLookupField = Schema::hasColumn('system_configs', 'lookup_field');
        $hasLookupValue = Schema::hasColumn('system_configs', 'lookup_value');
        $hasLabel = Schema::hasColumn('system_configs', 'label');
        $hasType = Schema::hasColumn('system_configs', 'type');

        $rows = [
            [
                'key' => 'dep_min',
                'value' => '50000',
                'source_type' => 'datamodel_lookup',
                'label' => 'Minimum Deposit',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'min deposit',
                'result_field' => 'value',
            ],
            [
                'key' => 'dep_mul_bank',
                'value' => '10',
                'source_type' => 'datamodel_lookup',
                'label' => 'Deposit Multiplier for Bank',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Multiply TO',
                'result_field' => 'value',
            ],
            [
                'key' => 'dep_mul_nonbank',
                'value' => '5',
                'source_type' => 'datamodel_lookup',
                'label' => 'Deposit Multiplier for Non-Bank',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Multiply TO Non Bank',
                'result_field' => 'value',
            ],
            [
                'key' => 'main_domain',
                'value' => '',
                'source_type' => $agentDomainsDataModelId !== null ? 'datamodel_lookup' : 'manual',
                'label' => 'main_domain',
                'type' => 'auto_update',
                'data_model_id' => $agentDomainsDataModelId,
                'lookup_field' => $agentDomainsDataModelId !== null ? 'utama' : null,
                'lookup_value' => $agentDomainsDataModelId !== null ? 'on' : null,
                'result_field' => $agentDomainsDataModelId !== null ? 'domain' : null,
            ],
            [
                'key' => 'ev_brt',
                'value' => '1',
                'description' => '1 = ACTIVE, 0 = NONACTIVE',
                'source_type' => 'datamodel_lookup',
                'label' => 'ev_brt',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue status',
                'result_field' => 'value',
            ],
            [
                'key' => 'ev_ap',
                'value' => '1',
                'description' => '1 = ACTIVE, 0 = NONACTIVE',
                'source_type' => 'datamodel_lookup',
                'label' => 'ev_ap',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi apk status',
                'result_field' => 'value',
            ],
            [
                'key' => 'ev_bd',
                'value' => '1',
                'description' => '1 = ACTIVE, 0 = NONACTIVE',
                'source_type' => 'datamodel_lookup',
                'label' => 'ev_bd',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi deposit status',
                'result_field' => 'value',
            ],
            [
                'key' => 'ev_frp',
                'value' => '1',
                'description' => '1 = ACTIVE, 0 = NONACTIVE',
                'source_type' => 'datamodel_lookup',
                'label' => 'ev_frp',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'free spin status',
                'result_field' => 'value',
            ],
            [
                'key' => 'ref_min',
                'value' => '20000',
                'source_type' => 'datamodel_lookup',
                'label' => 'ref_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman min depo',
                'result_field' => 'value',
            ],
            [
                'key' => 'ref_to',
                'value' => '30000',
                'source_type' => 'datamodel_lookup',
                'label' => 'ref_to',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman to depo',
                'result_field' => 'value',
            ],
            [
                'key' => 'ref_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'ref_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'ref_bet',
                'value' => '20000',
                'source_type' => 'datamodel_lookup',
                'label' => 'ref_bet',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman between bonus',
                'result_field' => 'value',
            ],
            [
                'key' => 'ref_gt',
                'value' => '50000',
                'source_type' => 'datamodel_lookup',
                'label' => 'ref_gt',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman greater bonus',
                'result_field' => 'value',
            ],
            [
                'key' => 'ev_ref',
                'value' => '1',
                'description' => '1 = ACTIVE, 0 = NONACTIVE',
                'source_type' => 'datamodel_lookup',
                'label' => 'ev_ref',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus ajak teman status',
                'result_field' => 'value',
            ],
            [
                'key' => 'brt_min',
                'value' => '50000',
                'source_type' => 'datamodel_lookup',
                'label' => 'brt_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue min amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'brt_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'brt_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'brt_max',
                'value' => '50000',
                'source_type' => 'datamodel_lookup',
                'label' => 'brt_max',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue max amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'brt_cnt',
                'value' => '8',
                'source_type' => 'datamodel_lookup',
                'label' => 'brt_cnt',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue count',
                'result_field' => 'value',
            ],
            [
                'key' => 'brt_nonbank',
                'value' => '0',
                'description' => '0 = FALSE , 1 = TRUE',
                'source_type' => 'datamodel_lookup',
                'label' => 'brt_nonbank',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus depo continue non bank include',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_day',
                'value' => '1',
                'description' => '1=Senin, 2=Selasa, 3=Rabu, 4=Kamis, 5=Jumat, 6=Sabtu, 7=Minggu',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_day',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus_cashback_day',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_type',
                'value' => 'game',
                'description' => 'game=By Game Loss, total=By Total Loss',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_type',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus bonuscashback',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_arc_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_arc_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_arcademinamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_arc_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_arc_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_arcaderate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_dd_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_dd_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_ddminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_dd_rate',
                'value' => '5',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_dd_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_ddrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_lc_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_lc_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_livecasinominamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_lc_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_lc_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_livecasinorate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_sa_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_sa_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_sabungayamminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_sa_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_sa_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_sabungayamrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_slot_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_slot_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_slotminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_slot_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_slot_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_slotrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_spt_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_spt_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_sportsminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_spt_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_spt_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_sportsrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_esp_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_esp_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_esportsminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_esp_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_esp_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_esportsrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tbl_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tbl_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_tablegameminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tbl_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tbl_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_tablegamerate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tgk_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tgk_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_tangkasminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tgk_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tgk_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_tangkasrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tgl_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tgl_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_togelminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tgl_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tgl_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_togelrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tot_min',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tot_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_totalminamount',
                'result_field' => 'value',
            ],
            [
                'key' => 'cb_tot_rate',
                'value' => '0',
                'source_type' => 'datamodel_lookup',
                'label' => 'cb_tot_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'Weekly Bonus cb_totalrate',
                'result_field' => 'value',
            ],
            [
                'key' => 'fs_min',
                'value' => '2000',
                'source_type' => 'datamodel_lookup',
                'label' => 'fs_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'free spin min amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'fs_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'fs_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'free spin multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'fs_nonbank',
                'value' => '0',
                'description' => '0 = FALSE , 1 = TRUE',
                'source_type' => 'datamodel_lookup',
                'label' => 'fs_nonbank',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'free spin non bank include',
                'result_field' => 'value',
            ],
            [
                'key' => 'bfd_b_min',
                'value' => '2000',
                'source_type' => 'datamodel_lookup',
                'label' => 'bfd_b_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi first bank min amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'bfd_b_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'bfd_b_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi first bank multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'bfd_b_rate',
                'value' => '10',
                'source_type' => 'datamodel_lookup',
                'label' => 'bfd_b_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi first bank rate bonus',
                'result_field' => 'value',
            ],
            [
                'key' => 'bdd_b_min',
                'value' => '2000',
                'source_type' => 'datamodel_lookup',
                'label' => 'bdd_b_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi daily bank min amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'bdd_b_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'bdd_b_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi daily bank multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'bdd_b_rate',
                'value' => '10',
                'source_type' => 'datamodel_lookup',
                'label' => 'bdd_b_rate',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi daily bank rate bonus',
                'result_field' => 'value',
            ],
            [
                'key' => 'bap_bon',
                'value' => '5000',
                'source_type' => 'datamodel_lookup',
                'label' => 'bap_bon',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi apk bonus amount',
                'result_field' => 'value',
            ],
            [
                'key' => 'bap_cou',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'bap_cou',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi apk count',
                'result_field' => 'value',
            ],
            [
                'key' => 'bap_mul',
                'value' => '1',
                'source_type' => 'datamodel_lookup',
                'label' => 'bap_mul',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'bonus misi apk multiplier',
                'result_field' => 'value',
            ],
            [
                'key' => 'wd_min',
                'value' => '1000',
                'source_type' => 'datamodel_lookup',
                'label' => 'wd_min',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'min withdraw',
                'result_field' => 'value',
            ],
            [
                'key' => 'apk_url',
                'value' => null,
                'source_type' => 'datamodel_lookup',
                'label' => 'apk_url',
                'type' => 'auto_update',
                'data_model_id' => $settingsDataModelId,
                'lookup_field' => 'kode',
                'lookup_value' => 'download apk url',
                'result_field' => 'value',
            ],
            [
                'key' => 'pola_gacor',
                'value' => 'POLA MAHJONG WAYS 1 - Turbo ON - Manual 10x - Turbo ON - Auto 10x - Turbo OFF - Manual 15x - Rekomendasi bet: 400 - 8.000 POLA WILD BANDITO - Turbo ON - Auto 30x - Turbo ON - Manual 18x - Turbo OFF - Auto 30x - Turbo ON - Manual 12x - Rekomendasi bet: 400 POLA MAHJONG WAYS 2 - Turbo ON - Manual 14x - Turbo ON - Auto 30x - Turbo OFF - Manual 10x - Rekomendasi bet: 400 - 8.000 POLA GATE OF OLYMPUS 1000 - ON/OFF/ON - 20 Auto DC ON - OFF/ON/ON - 10 Manual DC OFF - OFF/ON/ON - 30 Auto DC OFF - OFF/OFF/ON - 50 Manual DC ON - Buy Spin disarankan: 20 ribu x5 atau 60 ribu x3',
                'source_type' => 'manual',
                'label' => 'pola_gacor',
                'type' => 'manual',
                'data_model_id' => null,
                'lookup_field' => null,
                'lookup_value' => null,
                'result_field' => null,
            ],
            [
                'key' => 'game_gacor',
                'value' => 'PGSOFT: - Mahjong Ways 2 - Anubis Wrath - Candy Bonanza - Wild Bandito - Wild Bounty Showdown Pragmatic Play: - Fortune of Olympus - Gates of Olympus Dice - Sweet Bonanza Super Scatter - Starlight Archer 1000 - 5 Lions Megaways Fastspin: - Mahjong Princess - Caribbean Riches - Golden Moon Empire - Jungle Quest - Pai Gow Ways',
                'source_type' => 'manual',
                'label' => 'game_gacor',
                'type' => 'manual',
                'data_model_id' => null,
                'lookup_field' => null,
                'lookup_value' => null,
                'result_field' => null,
            ],
            [
                'key' => 'rtp_url',
                'value' => 'https://rtpcmbet95.xyz/',
                'source_type' => 'manual',
                'label' => 'rtp_url',
                'type' => 'manual',
                'data_model_id' => null,
                'lookup_field' => null,
                'lookup_value' => null,
                'result_field' => null,
            ],
        ];

        foreach ($rows as $row) {
            if ($hasLookupRules) {
                $row['lookup_rules'] = $row['source_type'] === 'datamodel_lookup'
                    ? json_encode([[
                        'field' => (string) ($row['lookup_field'] ?? 'kode'),
                        'operator' => '=',
                        'value' => (string) ($row['lookup_value'] ?? ''),
                    ]], JSON_UNESCAPED_UNICODE)
                    : null;

                unset($row['lookup_field'], $row['lookup_value']);
            }

            if (! $hasLookupField && array_key_exists('lookup_field', $row)) {
                unset($row['lookup_field']);
            }

            if (! $hasLookupValue && array_key_exists('lookup_value', $row)) {
                unset($row['lookup_value']);
            }

            if (! $hasLabel && array_key_exists('label', $row)) {
                unset($row['label']);
            }

            if (! $hasType && array_key_exists('type', $row)) {
                unset($row['type']);
            }

            SystemConfig::query()->updateOrCreate(
                ['key' => $row['key']],
                $row
            );
        }
    }
}
