<?php

namespace Database\Seeders;

use App\Models\DataModel;
use App\Models\Tool;
use Illuminate\Database\Seeder;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $playersModel = DataModel::query()->where('slug', 'players')->first();
        $playersDataModelId = $playersModel?->id;

        $depositModel = DataModel::query()->where('slug', 'deposit')->first();
        $withdrawModel = DataModel::query()->where('slug', 'withdraw')->first();
        $bonusApkModel = DataModel::query()->where('slug', 'bonus-apk')->first();
        $bonusBeruntunModel = DataModel::query()->where('slug', 'bonus-beruntun')->first();
        $bonusDepositModel = DataModel::query()->where('slug', 'bonus-deposit')->first();
        $bonusAjakTemanModel = DataModel::query()->where('slug', 'bonus-ajak-teman')->first();
        $bonusVoucherModel = DataModel::query()->where('slug', 'bonus-voucher')->first();
        $bonusFreespinModel = DataModel::query()->where('slug', 'bonus-freespin')->first();
        $promoModel = DataModel::query()->where('slug', 'promo')->first();
        $gameModel = DataModel::query()->where('slug', 'game')->first();
        $rekeningModel = DataModel::query()->where('slug', 'rekenings')->first();
        $providerModel = DataModel::query()->where('slug', 'providers')->first();
        $poolsPeriodeModel = DataModel::query()->where('slug', 'pools-periode')->first();

        $tools = [
            // ─── Internal config (no type) ───
            [
                'tool_name' => '_bot_config',
                'category' => 'system',
                'display_name' => 'Bot Config',
                'description' => 'Konfigurasi umum bot',
                'slug' => '_bot-config',
                'type' => 'info',
                'is_enabled' => false,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => null,
                'tool_rules' => null,
                'information_text' => null,
                'meta' => ['bot_name' => 'xoneBot'],
            ],

            // ─── UPDATE type tools (API endpoint) ───
            [
                'tool_name' => 'resetPassword',
                'category' => 'account',
                'display_name' => 'Reset Password',
                'description' => 'Reset password user Jika User meminta untuk reset pass / reset password',
                'slug' => 'reset-password',
                'type' => 'update',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'namarek' => ['type' => 'string', 'description' => 'Nama pemilik rekening'],
                        'norek' => ['type' => 'string', 'description' => 'Nomor rekening / Nomor Hp (E-wallet)'],
                        'bank' => ['type' => 'string', 'description' => 'Nama Bank'],
                    ],
                    'required' => ['namarek', 'norek', 'bank'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => 'https://api-stg.pilartestengine.com/aiservice/api/resetpassword',
                        'body' => [
                            // 'username' => '$arg->username',
                            'namarek' => '$arg->namarek',
                            'norek' => '$arg->norek',
                            'bank' => '$arg->bank',
                            'agent' => config('services.agent.kode'),
                        ],
                        'expected_response' => [
                            'status' => 200,
                            'message' => 'Success',
                            'data' => (object) [],
                        ],
                    ],
                    'chain_rules' => [
                        // [
                        //     'on'         => 'failure',
                        //     'condition'  => 'contains',
                        //     'field'      => 'response_message',
                        //     'value'      => 'balance greater than 10,000',
                        //     'chain_tool' => 'escalate',
                        //     'carry_args' => [],
                        //     'message'    => 'Balance Anda diatas 10.000 demi keamanan tolong kirimkan bukti transfer deposit terakhir anda, akan saya teruskan ke Human Support , harap tunggu sebentar ya',
                        // ],
                        [
                            'on'         => 'failure',
                            'condition'  => 'contains',
                            'field'      => 'response_message',
                            'value'      => 'Player is banned',
                            'chain_tool' => 'escalate',
                            'carry_args' => [],
                            'message'    => 'Mohon maaf, akun Anda saat ini dalam status banned. Kendala ini akan kami teruskan ke tim Human Support kami, harap tunggu sebentar ya.',
                        ],
                        [
                            'on'         => 'failure',
                            'condition'  => 'contains',
                            'field'      => 'response_message',
                            'value'      => 'balance greater than 100,000',
                            'chain_tool' => 'verifyDeposit',
                            'carry_args' => ['namarek', 'norek', 'bank'],
                            'message'    => 'Demi keamanan akun, saldo di atas batas perlu verifikasi tambahan. Boleh kami lanjutkan proses verifikasi sekarang? Silakan kirimkan bukti transfer deposit terakhir Anda.',
                        ],
                    ],
                ],
                // 'keywords' => ['Reset Password', 'reset pass'],
                'tool_rules' => "- Terima data user dalam format chat bebas\n- Format data yang dibutuhkan: namarek, norek, bank\n- Jika sebagian data sudah ada, cukup minta data yang masih kurang\n- Jangan eksekusi sebelum semua data wajib terkumpul lengkap\n- Setelah berhasil, infokan bahwa password berhasil direset ke 1234567 dan berikan link website untuk login\n- Jika data tidak cocok, minta player periksa kembali atau tawarkan untuk dibantu REGISTER",
                'information_text' => null,
                'meta' => null,
            ],
            // ─── VERIFY DEPOSIT (triggered from resetPassword on balance error) ───
            [
                'tool_name' => 'verifyDeposit',
                'category' => 'account',
                'display_name' => 'Verify Deposit',
                'description' => 'Verifikasi deposit saat reset password gagal karena balance melebihi ketentuan. AI menganalisa screenshot bukti transfer untuk mengekstrak jumlah (depoamount) dan waktu transfer (time), lalu mengirim data ke endpoint untuk diverifikasi.',
                'slug' => 'verify-deposit',
                'type' => 'update',
                'is_enabled' => false,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'namarek'    => ['type' => 'string', 'description' => 'Nama pemilik rekening'],
                        'norek'      => ['type' => 'string', 'description' => 'Nomor rekening / Nomor HP'],
                        'bank'       => ['type' => 'string', 'description' => 'Nama bank'],
                        'depoamount' => ['type' => 'string', 'description' => 'Jumlah transfer deposit (dari screenshot bukti transfer)'],
                        'time'       => ['type' => 'string', 'description' => 'Waktu transfer (dari screenshot bukti transfer)'],
                    ],
                    'required' => ['namarek', 'norek', 'bank', 'depoamount', 'time'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => 'https://api-stg.pilartestengine.com/aiservice/api/deposit/resetpassword',
                        'body' => [
                            'namarek'    => '$arg->namarek',
                            'norek'      => '$arg->norek',
                            'bank'       => '$arg->bank',
                            'agent'      => config('services.agent.kode'),
                            'depoamount' => '$arg->depoamount',
                            'time'       => '$arg->time',
                        ],
                        'expected_response' => [
                            'status'  => 200,
                            'message' => 'Success',
                            'data'    => (object) [],
                        ],
                    ],
                ],
                'tool_rules' => "- Tool ini dipanggil otomatis dari resetPassword ketika response gagal karena balance melebihi ketentuan\n- Data namarek, norek, bank sudah tersedia dari sesi resetPassword sebelumnya — jangan tanya ulang\n- Minta user mengirimkan screenshot bukti transfer deposit\n- Analisa gambar dan ekstrak: jumlah transfer (depoamount) dan waktu transfer (time) — nilai ini HANYA boleh diambil dari gambar screenshot, JANGAN mengambil dari teks chat, history, atau nilai parameter lain\n- Jika gambar bukan screenshot bukti transfer (tidak terlihat nominal dan waktu transaksi), set depoamount = '' dan time = '' lalu minta kirim ulang screenshot yang benar\n- Jangan eksekusi sebelum semua 5 data lengkap (namarek, norek, bank, depoamount, time)\n- Setelah berhasil, infokan bahwa password berhasil direset ke 1234567 dan berikan link website untuk login",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'register',
                'category' => 'account',
                'display_name' => 'Register',
                'description' => 'Mendaftarkan akun player baru',
                'slug' => 'register',
                'type' => 'update',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username untuk akun baru'],
                        // 'email' => ['type' => 'string', 'description' => 'Email untuk akun baru'],
                        // 'hp' => ['type' => 'string', 'description' => 'Nomor telepon/HP'],
                        'bank' => ['type' => 'string', 'description' => 'Nama bank'],
                        'namarek' => ['type' => 'string', 'description' => 'Nama pemilik rekening (bisa nama asli atau username/nickname yang terdaftar di bank, terima apa adanya)'],
                        'norek' => ['type' => 'string', 'description' => 'Nomor rekening'],
                    ],
                    'required' => ['username', 'bank', 'namarek', 'norek'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => 'https://api-stg.pilartestengine.com/aiservice/api/register',
                        'body' => [
                            'username' => '',
                            // 'email' => '',
                            // 'hp' => '',
                            'bank' => '',
                            'namarek' => '',
                            'norek' => '',
                            'agent' => config('services.agent.kode'),
                        ],
                        'expected_response' => [
                            'status' => 200,
                            'message' => 'Success',
                            'data' => (object) [],
                        ],
                    ],
                ],
                // 'keywords' => ['register', 'daftar', 'registrasi', 'buat akun', 'sign up', 'signup', 'mendaftar'],
                'tool_rules' => "- Terima data registrasi dalam format chat bebas, tidak harus list atau urutan tertentu\n- Jika sebagian data sudah ada, cukup minta data yang masih kurang: username, bank, nama rekening, atau nomor rekening\n- Tidak perlu meminta password\n- Validasi format inti: norek harus numerik\n- Jangan eksekusi sebelum semua data lengkap\n- Setelah berhasil registrasi, ucapkan selamat dan berikan panduan login dengan password 1234567 dan berikan link ke website untuk login",
                'information_text' => null,
                'meta' => null,
            ],

            // ─── GET type tools (DataModel lookup) ───
            [
                'tool_name' => 'checkSuspend',
                'category' => 'account',
                'display_name' => 'Cek Suspend',
                'description' => 'Cek apakah akun player sedang di-suspend',
                'slug' => 'check-suspend',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $playersDataModelId,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username to check suspend status'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                // 'keywords' => ['suspend', 'check suspend', 'status', 'suspended', 'cek suspend', 'suspend status'],
                'tool_rules' => "- Jika username belum ada, minta username secara natural tanpa memaksa format tertentu\n- Cek field 'banned_at': jika null berarti TIDAK suspend, jika ada tanggal berarti SUSPEND\n- Jika suspend, infokan bahwa akunnya sedang dalam status suspend dan masalah akan diteruskan ke Human Support\n- Jika tidak suspend, infokan bahwa akun dalam kondisi normal/aktif",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'toStatus',
                'category' => 'account',
                'display_name' => 'Status TurnOver',
                'description' => 'Menyediakan informasi status TurnOver (TO) untuk player',
                'slug' => 'to-status',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $playersDataModelId,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username untuk cek status TurnOver'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                // 'keywords' => ['to', 'turnover', 'status to', 'jumlah to', 'target to'],
                'tool_rules' => "- Jika username belum ada, minta username secara natural\n- Tampilkan hanya field 'to' (TO saat ini) dan 'targetTo' (target TO)\n- Hitung sisa TO: targetTo - to\n- Jika TO sudah tercapai, infokan bisa withdraw\n- Jika belum, infokan sisa TO yang harus dipenuhi",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'promo',
                'category' => 'promo',
                'display_name' => 'Promo',
                'description' => 'Menyediakan informasi Promo. Menampilkan promo aktif yang sedang berjalan.',
                'slug' => 'promo',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $promoModel?->id,
                'parameters' => null,
                'endpoints' => null,
                // 'keywords' => ['promo', 'list promo', 'daftar promo'],
                'tool_rules' => "- Tool ini KHUSUS untuk promo/event/banner/promosi yang sedang berjalan\n- Jangan gunakan tool ini untuk pertanyaan bonus umum, klaim bonus, cashback, referral, atau syarat bonus; untuk itu jawab dari Knowledge Base bagian Bonus\n- Pertama tampilkan HANYA daftar title promo aktif beserta ringkasan singkat (1 kalimat) dari body\n- Jangan tampilkan isi body lengkap kecuali customer bertanya detail promo tertentu\n- Jika customer minta detail, barulah berikan body lengkap promo tersebut\n- Jika ada buttonlink, sertakan linknya\n- Jika tidak ada promo aktif, sampaikan belum tersedia",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['title', 'body', 'category', 'buttonlink'],
                        'filters' => [
                            ['field' => 'status', 'operator' => '=', 'value' => 'active'],
                        ],
                        'date_range' => [
                            'mode' => 'between_now',
                            'start_field' => 'start_date',
                            'end_field' => 'end_date',
                        ],
                        'order_by' => [
                            'field' => 'urutan',
                            'direction' => 'asc',
                        ],
                    ],
                ],
            ],
            [
                'tool_name' => 'checkGame',
                'category' => 'games',
                'display_name' => 'Cek Game',
                'description' => 'Cek ketersediaan dan info game berdasarkan keyword.',
                'slug' => 'check-game',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $gameModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'keyword' => ['type' => 'string', 'description' => 'Kata kunci untuk mencari game berdasarkan nama, provider, kategori, atau keyword terkait. Boleh sebagian, contoh: "maja" untuk mencari "Mahjong Ways", atau "live" untuk mencari semua game dengan kategori live casino.'],
                    ],
                ],
                'endpoints' => null,
                // 'keywords' => ['game', 'slot', 'casino', 'provider', 'cek game', 'ada game', 'game aktif', 'cari game', 'game apa', 'live casino', 'sportbook', 'togel', 'arcade', 'fishing'],
                'tool_rules' => "- Cari game berdasarkan field name, provider, category, atau keyword\n- Tampilkan: name, provider, category\n- Jika ditemukan banyak hasil, tampilkan maksimal 10 dan infokan masih ada lainnya\n- Jika tidak ditemukan, sampaikan game tidak tersedia\n- Tampilkan gambar hanya jika diminta: gunakan URL https://devasset.pilartestengine.com/assets + nilai field image, kirim dalam bentuk file image",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => [],
                        // Conditions: all rows must have isshow=1 (static),
                        // then match the customer's search term across name/keyword/provider/category (OR group).
                        'conditions' => [
                            [
                                'field'    => 'isshow',
                                'operator' => '=',
                                'source'   => 'static',
                                'value'    => 1,
                            ],
                            [
                                'field'          => 'keyword',
                                'operator'       => 'LIKE%%',
                                'source'         => 'arg',
                                'arg'            => 'keyword',
                                'group'          => 1,
                                'skip_if_empty'  => true,
                            ],
                        ],
                        'order_by' => [
                            'field'     => 'urutan',
                            'direction' => 'asc',
                        ],
                        'limit' => 10,
                    ],
                ],
            ],
            [
                'tool_name' => 'Rekening',
                'category' => 'payment',
                'display_name' => 'Rekening',
                'description' => 'Menyediakan informasi list Rekening Web yang "Active"',
                'slug' => 'rekening',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $rekeningModel?->id,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => null,
                'tool_rules' => "- - List rekening Active yang ada pada Website / Platform\n- Listkan semua Rekening\n- Berikan detail bank, nama, norek\n- Bank yang di list adalah untuk Manual Deposit",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => [],
                        'conditions' => [
                            [
                                'field' => 'bank',
                                'operator' => '!=',
                                'source' => 'static',
                                'value' => 'Auto Bank',
                            ],
                        ],
                        'order_by' => [
                            'field' => 'seq',
                            'direction' => 'asc',
                        ],
                        'limit' => 50,
                    ],
                ],
            ],
            // [
            //     'tool_name' => 'listProviders',
            //     'category' => 'games',
            //     'display_name' => 'List Provider',
            //     'description' => 'Menampilkan daftar provider game yang tersedia. Bisa filter berdasarkan nama atau alias provider.',
            //     'slug' => 'list-providers',
            //     'type' => 'get_multiple',
            //     'is_enabled' => true,
            //     'data_model_id' => $providerModel?->id,
            //     'parameters' => [
            //         'type' => 'object',
            //         'properties' => [
            //             'name' => ['type' => 'string', 'description' => 'Kata kunci nama atau alias provider. Boleh sebagian: "pg", "pragmatic", "micro", dll. Kosongkan untuk tampilkan semua provider aktif.'],
            //         ],
            //         'required' => [],
            //     ],
            //     'endpoints' => null,
            //     'tool_rules' => "- Kirim kata kunci apa adanya dari user, jangan ubah atau perluas\n- Contoh: user bilang \"pg\" → kirim name=\"pg\"; user bilang \"pragmatic\" → kirim name=\"pragmatic\"\n- Jika user hanya tanya \"ada provider apa\" atau \"list provider\" tanpa kata kunci → panggil tanpa parameter\n- Pencarian berlaku di field name dan alias secara bersamaan\n- Tampilkan: name, alias, category\n- Jika tidak ditemukan, sampaikan provider tidak tersedia",
            //     'information_text' => null,
            //     'keywords' => null,
            //     'meta' => [
            //         'query' => [
            //             'select' => ['name', 'alias', 'category'],
            //             'filters' => [
            //                 ['field' => 'active', 'operator' => '=', 'value' => 1],
            //             ],
            //             'search_fields' => ['name', 'alias'],
            //             'order_by' => [
            //                 'field' => 'urutan',
            //                 'direction' => 'asc',
            //             ],
            //         ],
            //     ],
            // ],

            // ─── INFO type tools (static information) ───
            // [
            //     'tool_name' => 'game_gacor',
            //     'category' => 'games',
            //     'display_name' => 'Game Gacor',
            //     'description' => 'Bocoran Slot Gacor terbaru hari ini. Hanya ambil informasi dari list yang tersedia. Jangan buat konten baru.',
            //     'slug' => 'game-gacor',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['game gacor', 'slot gacor', 'bocoran slot'],
            //     'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat konten baru\n- Gunakan emoji dan format menarik untuk presentasi\n- Jika ditanya game yang tidak ada di list, bilang tidak tersedia dan tawarkan yang ada",
            //     'information_text' =>[
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Mahjong Ways 2\n- Anubis Wrath\n- Candy Bonanza\n- Wild Bandito\n- Wild Bounty Showdown\n\n🎰 Pragmatic Play\n- Fortune of Olympus\n- Gates of Olympus Dice\n- Sweet Bonanza Super Scatter\n- Starlight Archer 1000\n- 5 Lions Megaways\n\n🎰 Fastspin\n- Mahjong Princess\n- Caribbean Riches\n- Golden Moon Empire\n- Jungle Quest\n- Pai Gow Ways",
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Anubis Wrath\n- Buffalo Win\n- Mahjong Ways\n- Sun & Moon\n- Cash Mania\n\n🎰 Pragmatic Play\n- Gates of Olympus 1000\n- Mahjong Wins 2 100.000x\n- Mahjong Wins 3 Black Scatter\n- Sweet Bonanza Super Scatter\n- Triple Pot Gold\n\n🎰 Spade Gaming\n- Clash of the Giants\n- Royale Vegas\n- Brothers Kingdom 2\n- Gold Panther Maxways\n- Roma",
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Candy Burst\n- Treasures of Aztec\n- Crypto Gold\n- Emoji Riches\n- Mafia Mayhem\n\n🎰 Pragmatic Play\n- Mahjong Wins 3 Black Scatter\n- Gates of Olympus 1000\n- Gates of Gatot Kaca 1000\n- Starlight Princess 1000\n- Aztec Gems\n\n🎰 Nolimit City\n- Poison Eve\n- The Crypt\n- Bounty Hunters\n- Disturbed\n- Dead Wood",
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Mahjong Ways 2\n- Wild Bounty Showdown\n- Wild Bandito\n- Wild Ape\n- Treasures of Aztec\n\n🎰 Pragmatic Play\n- Starlight Christmas\n- Gates of Olympus Super Scatter\n- Sweet Bonanza\n- Triple Pot Gold\n- Mahjong Wins 3 Black Scatter\n\n🎰 Microgaming\n- Candy Rush Wilds 2\n- Lucky Twins Wilds\n- 10000 Fortunes\n- 777 Royal Wheel\n- 22 Skulls of the Dead",
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Bakery Bonanza\n- Buffalo Win\n- Alibaba's Cave of Fortune\n- Candy Bonanza\n- Bikini Paradise\n\n🎰 Pragmatic Play\n- Gates of Olympus Super Scatter\n- Gates of Gatot Kaca Super Scatter\n- Pyramid Bonanza\n- Sweet Bonanza\n- Sugar Rush 1000\n\n🎰 Spade Gaming\n- Clash of the Giants\n- Fury Max Lucky Road\n- Royale Vegas\n- Roma\n- Sugar Party",
            //          "🔥🔥 Bocoran Slot Hari Ini 🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\n🎰 PGSOFT\n- Mahjong Ways\n- Buffalo Win\n- Captain's Bounty\n- Candy Bonanza\n- The Great Icescape\n\n🎰 Pragmatic Play\n- Forge of Olympus\n- Starlight Princess 1000\n- Pyramid Bonanza\n- Sweet Bonanza\n- Wild Booster\n\n🎰 Wonwon\n- Olympus 8000\n- Mahjong Mania\n- Zeus\n- Ganesha\n- Dragon Mystery",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'pola_gacor',
            //     'category' => 'games',
            //     'display_name' => 'Pola Gacor',
            //     'description' => 'Pola Gacor terbaru hari ini. Hanya ambil informasi dari list yang tersedia. Jangan buat konten baru.',
            //     'slug' => 'pola-gacor',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['pola gacor', 'pola vip', 'pola vvip', 'pola mantap', 'pola terbaik'],
            //     'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat pola baru\n- Tampilkan pola dengan format asli termasuk emoji ✅❌\n- Jika ditanya game yang tidak ada polanya, bilang belum tersedia",
            //     'information_text' => "𝐏𝐎𝐋𝐀 𝐕𝐈𝐏  𝐓𝐄𝐑𝐔𝐏𝐃𝐀𝐓𝐄 𝐇𝐀𝐑𝐈 𝐈𝐍𝐈!\nPOLA MAHJONG WAYS 1\nTurbo ✅– MANUAL Spin 10x\nTurbo ✅- AUTO Spin 10x\nTurbo ❌– MANUAL Spin 15x\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400 - 8.000\n\nPOLA WILD BANDITO\nTurbo ✅ – Auto 30\nTurbo ✅ – Manual 18\nTurbo ❌ – Auto 30\nTurbo ✅ – Manual 12\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400\n\nPOLA Mahjong Ways 2\nTurbo ✅– MANUAL Spin 14x\nTurbo ✅- AUTO Spin 30x\nTurbo ❌– MANUAL Spin 10x\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400 - 8.000\n\n📌𝐏𝐎𝐋𝐀 𝐓𝐄𝐑𝐁𝐀𝐈𝐊 \n📈 𝐆𝐚𝐭𝐞 𝐎𝐟 𝐎𝐥𝐲𝐦𝐩𝐮𝐬 𝟏.𝟎𝟎𝟎⚡️\n-----------------------\n✅❌✅ - 20 AUTO DC ON\n❌✅✅ - 10 MANUAL DC OFF\n❌✅✅ - 30 AUTO DC OFF\n❌❌✅ - 50 MANUAL DC ON\n🔔𝐁𝐔𝐘 𝐒𝐏𝐈𝐍 𝐘𝐀𝐍𝐆 𝐃𝐈𝐒𝐀𝐑𝐀𝐍𝐊𝐀𝐍 𝟐𝟎 𝐑𝐈𝐁𝐔 𝐗5\n🔔𝐁𝐔𝐘 𝐒𝐏𝐈𝐍 𝐘𝐀𝐍𝐆 𝐃𝐈𝐒𝐀𝐑𝐀𝐍𝐊𝐀𝐍 6𝟎 𝐑𝐈𝐁𝐔 𝐗3",
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'bonus',
            //     'category' => 'bonus',
            //     'display_name' => 'Bonus',
            //     'description' => 'Informasi tentang klaim bonus dan syarat yang berlaku',
            //     'slug' => 'bonus',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['bonus claim', 'klaim bonus', 'bonus', 'bonus reward'],
            //     'tool_rules' => "- Infokan cara klaim bonus melalui menu Reward\n- Jika ditanya bonus spesifik, jelaskan bahwa semua bonus bisa diklaim dari menu Reward sebelum bermain\n- Gunakan tone ramah dan semangat",
            //     'information_text' => ['Halo Kak! Sebelum mulai bermain, jangan lupa untuk melakukan klaim bonusnya terlebih dahulu melalui menu Reward ya'],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'reward_claim_info',
            //     'category' => 'bonus',
            //     'display_name' => 'Reward Claim Info',
            //     'description' => 'Informasi mengapa member tidak bisa klaim bonus di menu Reward',
            //     'slug' => 'reward-claim-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['tidak bisa klaim', 'gagal klaim', 'klaim reward', 'bonus hilang', 'bonus expired', 'bonus deposit gratis', 'reward tidak bisa', 'klaim bonus reward', 'bonus tidak muncul'],
            //     'tool_rules' => "- Jelaskan bahwa bonus harus diklaim SEBELUM bermain melalui menu Reward\n- Jika tidak diklaim sebelum bermain, bonus akan otomatis expired\n- Jika member sudah terlanjur bermain tanpa klaim, jelaskan bahwa bonus tidak hilang secara permanen\n- Member bisa deposit kembali dan klaim ulang bonus di menu Reward sebelum bermain\n- Gunakan tone ramah dan meyakinkan agar member tidak khawatir",
            //     'information_text' => [
            //         "Klaim bonus harus dilakukan SEBELUM bermain ya Kak. Jika kakak tidak melakukan klaim sebelum bermain, maka bonus akan otomatis expired.",
            //         "Tapi tenang Kak, bonus deposit gratis kakak tidak hilang. Jika kakak deposit kembali, kakak bisa klaim ulang bonusnya di menu Reward sebelum bermain. Jadi pastikan selalu klaim bonus dulu sebelum mulai bermain ya Kak! 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'bonus_misi_deposit_beruntun',
            //     'category' => 'bonus',
            //     'display_name' => 'Bonus Misi Deposit Beruntun',
            //     'description' => 'Menjelaskan apa itu bonus misi deposit beruntun, cara kerja, syarat, dan cara mendapatkannya.',
            //     'slug' => 'bonus-misi-deposit-beruntun',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['misi deposit beruntun', 'bonus deposit beruntun', 'deposit beruntun', 'misi beruntun', 'bonus misi', 'deposit hari berturut', 'bonus harian deposit', 'misi deposit harian', 'bonus streak deposit', 'deposit berturut-turut'],
            //     'tool_rules' => "- Jelaskan bahwa bonus misi deposit beruntun didapat dengan melakukan deposit secara berturut-turut setiap hari\n- Sebutkan bahwa semakin banyak hari beruntun, semakin besar bonus yang didapat\n- Ingatkan member untuk klaim bonus di menu Reward sebelum bermain\n- Gunakan tone ramah dan semangat",
            //     'information_text' => [
            //         "Halo Kak! Bonus Misi Deposit Beruntun adalah bonus spesial yang bisa Kakak dapatkan dengan melakukan deposit setiap hari secara berturut-turut. Semakin banyak hari beruntun Kakak deposit, semakin besar bonus yang akan Kakak terima! Jangan lupa klaim bonusnya di menu Reward sebelum mulai bermain ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'wd_charge_info',
            //     'category' => 'payment',
            //     'display_name' => 'WD Charge Info',
            //     'description' => 'Informasi charge penarikan (WD) 2,5% jika lebih dari 5 kali per hari',
            //     'slug' => 'wd-charge-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['wd tidak sesuai', 'withdraw tidak sesuai', 'wd kurang', 'withdraw kurang', 'wd charge', 'potongan wd', 'wd dipotong', 'transfer tidak sesuai', 'nominal wd beda', 'wd terpotong', 'charge wd', 'biaya wd'],
            //     'tool_rules' => "- Jelaskan bahwa ada charge 2.5% jika melakukan WD lebih dari 5 kali dalam sehari\n- Sampaikan dengan tone ramah dan informatif\n- Sarankan member untuk mengatur jumlah WD agar tidak melebihi 5 kali per hari untuk menghindari charge",
            //     'information_text' => [
            //         "Kakak terkena charge 2,5% ya Kak, karena WD (withdraw) kakak sudah lebih dari 5 kali dalam sehari. Untuk menghindari charge ini, disarankan agar kakak mengatur penarikan tidak lebih dari 5 kali per hari ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'ewallet_premium_info',
            //     'category' => 'payment',
            //     'display_name' => 'E-Wallet Premium Info',
            //     'description' => 'Informasi bahwa E-Wallet harus berstatus Premium untuk transaksi',
            //     'slug' => 'ewallet-premium-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['ewallet', 'e-wallet', 'ewallet premium', 'rek ewallet', 'dompet digital', 'wajib premium', 'premium ewallet', 'upgrade ewallet'],
            //     'tool_rules' => "- Jelaskan bahwa semua akun E-Wallet WAJIB berstatus Premium\n- Sarankan member untuk upgrade E-Wallet terlebih dahulu sebelum mendaftar atau melakukan transaksi\n- Gunakan tone ramah dan informatif",
            //     'information_text' => [
            //         "Halo Kak, untuk penggunaan E-Wallet di situs kami, semua akun diwajibkan sudah berstatus Premium. Silakan pastikan E-Wallet Kakak sudah di-upgrade sebelum melakukan pendaftaran atau transaksi ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'situs_partner_info',
            //     'category' => 'general',
            //     'display_name' => 'Situs Partner Info',
            //     'description' => 'Menyediakan informasi bahwa situs partner hanya sebagai partner, bukan bagian dari perusahaan yang sama.',
            //     'slug' => 'situs-partner-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['situs partner', 'partner', 'satu company', 'satu perusahaan', 'afiliasi', 'hubungan situs', 'situs lain', 'sister site'],
            //     'tool_rules' => "- Jelaskan bahwa situs partner hanya sebagai partner saja, bukan satu company\n- Jangan memberikan informasi lebih lanjut mengenai detail internal perusahaan\n- Gunakan tone ramah dan singkat",
            //     'information_text' => [
            //         "Hanya sebagai situs partner saja ya Kak, bukan satu company 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_lose_info',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Lose Info',
            //     'description' => 'Menyediakan informasi tentang apa yang terjadi jika satu pertandingan di tiket Mix Parlay kalah.',
            //     'slug' => 'parlay-lose-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['parlay kalah', 'mix parlay', 'parlay lose', 'tiket parlay', 'parlay gugur', 'parlay kalah satu', 'parlay salah satu kalah'],
            //     'tool_rules' => "- Jelaskan bahwa jika satu pertandingan saja kalah (Lose), seluruh tiket Mix Parlay gugur/kalah total\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Jika ada satu saja pertandingan yang tebakannya salah atau kalah penuh (Lose), maka seluruh tiket Mix Parlay tersebut dinyatakan gugur atau kalah total ya Kak.",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_draw_info',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Draw Info',
            //     'description' => 'Menyediakan informasi tentang apa yang terjadi jika pertandingan di tiket Mix Parlay berakhir seri (Draw).',
            //     'slug' => 'parlay-draw-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['parlay seri', 'parlay draw', 'pertandingan seri', 'parlay hasil seri', 'odds draw', 'draw parlay'],
            //     'tool_rules' => "- Jelaskan bahwa pertandingan seri (Draw) tidak membuat tiket gugur\n- Odds pertandingan seri diubah menjadi 1 (tidak mempengaruhi perkalian)\n- Tiket tetap berjalan dengan sisa pertandingan lainnya\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Jika tebakan hasilnya seri (dan tidak ada sistem handicap yang memenangkan salah satu pihak), maka status pertandingan tersebut dianggap Draw. Nilai odds untuk pertandingan yang seri akan diubah menjadi 1 (tidak mempengaruhi perkalian), dan tiket tetap berjalan dengan sisa pertandingan lainnya ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_won_half_info',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Won Half Info',
            //     'description' => 'Informasi Menang Setengah (Won Half) di Mix Parlay',
            //     'slug' => 'parlay-won-half-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['menang setengah', 'won half', 'parlay menang setengah', 'half win', 'parlay half', 'setengah menang', 'menang setengah parlay', 'hitung odds menang setengah', 'rumus won half', 'perhitungan odds half'],
            //     'tool_rules' => "- Jelaskan konsep Menang Setengah (Won Half) dalam konteks Parlay\n- Jelaskan bahwa tiket tetap hidup tetapi odds dihitung ulang dengan rumus khusus\n- Jelaskan rumus perhitungan odds: (Odds awal - 1) / 2 + 1\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Menang Setengah (Won Half) terjadi jika tim yang dipilih menang berdasarkan sistem handicap (voor), tetapi selisih golnya hanya mencapai setengah dari nilai handicap tersebut. Tiket tetap hidup ya Kak, tetapi nilai odds tim tersebut akan dihitung ulang dengan rumus khusus sebelum dikalikan dengan tim lain 😊",
            //         "Rumus untuk menghitung odds Menang Setengah: (Nilai Odds awal - 1) dibagi 2, kemudian ditambah 1. Hasil angka ini yang akan dikalikan dengan odds pertandingan lainnya ya Kak.",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_odds_calculation',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Odds Calculation',
            //     'description' => 'Menyediakan informasi cara menghitung total odds di Mix Parlay dengan mengalikan semua odds pertandingan yang dipilih.',
            //     'slug' => 'parlay-odds-calculation',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['hitung odds parlay', 'total odds', 'kalkulasi parlay', 'cara hitung parlay', 'odds parlay', 'perhitungan parlay', 'rumus parlay', 'hitung mix parlay'],
            //     'tool_rules' => "- Jelaskan bahwa total odds dihitung dengan mengalikan semua odds pertandingan yang dipilih\n- Berikan contoh perhitungan jika diperlukan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Total odds dalam Mix Parlay dihitung dengan mengalikan semua odds dari pertandingan yang Kakak pilih. Misalnya, jika Kakak memilih 3 tim dengan odds 1.80, 2.00, dan 1.50, maka total odds adalah: 1.80 x 2.00 x 1.50 = 5.40 ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_payout_calculation',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Payout Calculation',
            //     'description' => 'Menyediakan informasi cara menghitung total kemenangan atau payout di Mix Parlay.',
            //     'slug' => 'parlay-payout-calculation',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['payout parlay', 'kemenangan parlay', 'hitung kemenangan', 'total kemenangan', 'keuntungan parlay', 'profit parlay', 'hitung payout', 'hasil parlay'],
            //     'tool_rules' => "- Jelaskan rumus: total odds x modal taruhan = total payout, lalu kurangi modal untuk keuntungan bersih\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Total kemenangan dihitung dengan mengalikan total odds dengan nominal modal taruhan Kakak, kemudian dikurangi dengan modal awal tersebut jika ingin melihat keuntungan bersih ya Kak. Contoh: total odds 5.40 x modal 100rb = 540rb (payout), keuntungan bersih = 540rb - 100rb = 440rb 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'parlay_void_postponed_info',
            //     'category' => 'sports',
            //     'display_name' => 'Parlay Void / Postponed Info',
            //     'description' => 'Menyediakan informasi tentang apa yang terjadi jika pertandingan di Mix Parlay dibatalkan, ditunda, atau void.',
            //     'slug' => 'parlay-void-postponed-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['parlay batal', 'pertandingan batal', 'postponed', 'parlay void', 'match batal', 'pertandingan ditunda', 'parlay ditunda', 'void parlay'],
            //     'tool_rules' => "- Jelaskan bahwa pertandingan yang batal/ditunda akan dianggap Void\n- Odds pertandingan Void diubah menjadi 1 (tidak mempengaruhi tiket)\n- Sisa tiket tetap berjalan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Jika pertandingan dibatalkan atau ditunda melewati batas waktu tertentu (biasanya 24 jam), pertandingan tersebut akan dianggap batal (Void). Nilai odds untuk pertandingan itu akan diubah menjadi 1, sehingga tidak mempengaruhi status menang/kalah dari sisa tiket Parlay Kakak ya 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'handicap_info',
            //     'category' => 'sports',
            //     'display_name' => 'Handicap (HDP) Info',
            //     'description' => 'Informasi sistem HDP atau Asian Handicap di taruhan olahraga',
            //     'slug' => 'handicap-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['hdp', 'handicap', 'asian handicap', 'voor', 'voor gol', 'apa itu hdp', 'apa itu handicap', 'sistem voor'],
            //     'tool_rules' => "- Jelaskan konsep HDP / Asian Handicap secara sederhana\n- Jelaskan bahwa tim kuat memberi voor ke tim lemah untuk menyeimbangkan peluang\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "HDP atau Asian Handicap adalah sistem pemberian nilai tambah atau kurang (voor) berupa gol kepada salah satu tim. Tim yang lebih kuat biasanya akan memberikan voor kepada tim yang lebih lemah untuk menyeimbangkan peluang ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'over_under_info',
            //     'category' => 'sports',
            //     'display_name' => 'Over/Under (O/U) Info',
            //     'description' => 'Menyediakan informasi tentang jenis taruhan Over/Under (O/U), menjelaskan cara prediksi total gol.',
            //     'slug' => 'over-under-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['over under', 'o/u', 'over/under', 'atas bawah', 'total gol', 'apa itu over under', 'apa itu o/u', 'ou'],
            //     'tool_rules' => "- Jelaskan konsep Over/Under secara sederhana\n- Jelaskan bahwa pemain menebak total gol di atas atau di bawah batas yang ditentukan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Over/Under (Atas/Bawah) adalah jenis taruhan di mana pemain menebak total gol yang tercipta dalam suatu pertandingan, apakah berada di atas (Over) atau di bawah (Under) batas angka yang telah ditentukan ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => '1x2_info',
            //     'category' => 'sports',
            //     'display_name' => '1x2 Info',
            //     'description' => 'Menyediakan informasi tentang format taruhan 1x2, menjelaskan Home win, Draw, dan Away win.',
            //     'slug' => '1x2-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['1x2', 'apa itu 1x2', 'taruhan 1x2', 'home draw away', '1 x 2', 'format 1x2'],
            //     'tool_rules' => "- Jelaskan format taruhan 1x2 secara sederhana\n- Jelaskan arti 1 (Home), X (Draw), 2 (Away)\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "1x2 adalah format taruhan klasik tanpa handicap ya Kak. Angka \"1\" mewakili kemenangan tuan rumah (Home), \"X\" mewakili hasil seri (Draw), dan \"2\" mewakili kemenangan tim tamu (Away) 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'odd_even_info',
            //     'category' => 'sports',
            //     'display_name' => 'Odd/Even (O/E) Info',
            //     'description' => 'Menyediakan informasi tentang jenis taruhan Odd/Even (O/E), menjelaskan cara menebak total gol ganjil atau genap.',
            //     'slug' => 'odd-even-info',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['odd even', 'o/e', 'odd/even', 'ganjil genap', 'apa itu odd even', 'apa itu o/e', 'taruhan ganjil genap'],
            //     'tool_rules' => "- Jelaskan konsep Odd/Even secara sederhana\n- Jelaskan bahwa pemain menebak total gol ganjil atau genap\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
            //     'information_text' => [
            //         "Odd/Even (Ganjil/Genap) adalah taruhan yang menebak apakah total keseluruhan gol dari kedua tim yang bertanding pada akhir laga akan bernilai ganjil atau genap ya Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'link_rtp',
            //     'category' => 'games',
            //     'display_name' => 'Link RTP',
            //     'description' => 'Link RTP slot dengan winrate game tertinggi',
            //     'slug' => 'link-rtp',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['link rtp', 'rtp', 'link anti rungkat'],
            //     'tool_rules' => "- Berikan link RTP dari information text\n- Jelaskan bahwa link tersebut menampilkan winrate game tertinggi secara realtime\n- Jangan buat atau tebak link sendiri",
            //     'information_text' => ["klik link untuk cek rtp kami disini dengan winrate game tertinggi kak 🙂\n- realtime - akurat - anti rungkat -\n\nhttps://rtpbigmsg77.xyz\n\ndan sudah tersedia jadwal dan pola gacor nya kak"],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'link_apk',
            //     'category' => 'games',
            //     'display_name' => 'Link APK',
            //     'description' => 'Menyediakan link untuk download APK aplikasi. Pastikan link dari sumber terpercaya untuk keamanan.',
            //     'slug' => 'link-apk',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['link apk', 'download apk', 'apk', 'url apk'],
            //     'tool_rules' => "- Berikan link APK dari information text\n- Jangan buat atau tebak link sendiri, gunakan HANYA link yang tersedia\n- Ajak user untuk mendaftar atau bermain dengan nada ramah dan semangat",
            //     'information_text' => ["silahkan akses link apk untuk daftar ataupun bermain di cmbet ya kak\n\nhttps://apk.hi11office.com/CMBET(2.0.6).apk\n\nselamat bermain dan semoga beruntung"],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'depositPulsa',
            //     'category' => 'payment',
            //     'display_name' => 'Deposit Pulsa',
            //     'description' => 'Menyediakan panduan langkah demi langkah cara deposit melalui pulsa. Mencakup proses top-up XL dan Telkomsel melalui form deposit website.',
            //     'slug' => 'deposit-pulsa',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['deposit pulsa', 'pulsa'],
            //     'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat panduan sendiri\n- Jelaskan langkah-langkah dengan format yang rapi dan mudah dipahami\n- Tekankan bahwa player harus mencantumkan SN atau nomor pengirim di kolom keterangan\n- Jika ditanya metode deposit lain selain pulsa, arahkan untuk menghubungi CS atau cek menu deposit di website",
            //     'information_text' => ["Cara depo melalui pulsa:\nKakak buka website kami, lalu ke menu form deposit. Setelah itu kakak pilih tujuan pulsa XL atau Telkomsel. Setelah itu kakak isi pulsa ke nomor tersebut, dan setelah sukses, kakak isi form deposit nya sesuai dengan nominal pulsa yang kakak isi. Jangan lupa di kolom keterangan kakak isi/cantumkan SN nya atau nomor pengirim (jika transfer pulsa), lalu ajukan form deposit nya."],
            //     'meta' => null,
            // ],

            // ─── GET MULTIPLE type tools ───
            [
                'tool_name' => 'BonusCashback',
                'category' => 'bonus',
                'display_name' => 'Bonus Cashback',
                'description' => 'Menyediakan informasi tentang bonus cashback. Bonus Cashback dibagikan setiap hari Senin.',
                'slug' => 'bonus-cashback',
                'type' => 'get_multiple',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                'tool_rules' => "- Bandingkan total amount Deposit vs Withdraw minggu lalu (Senin-Minggu) dengan status 'accept'\n- Jika Withdraw > Deposit = tidak dapat cashback (sudah profit)\n- Jika Deposit > Withdraw = berhak cashback dari selisihnya\n- Tampilkan: total deposit, total withdraw, selisih, dan status kelayakan\n- Format angka dengan separator ribuan",
                'information_text' => null,
                'meta' => [
                    'data_model_ids' => array_filter([
                        $depositModel?->id,
                        $withdrawModel?->id,
                    ]),
                    'query' => [
                        'filters' => [
                            ['field' => 'status', 'operator' => '=', 'value' => 'accept'],
                        ],
                        'date_range' => [
                            'field' => 'date',
                            'range' => 'last_week',
                        ],
                        'aggregate' => [
                            'function' => 'sum',
                            'field' => 'amount',
                        ],
                        'order_by' => [
                            'field' => 'id',
                            'direction' => 'desc',
                        ],
                    ],
                ],
            ],
            // [
            //     'tool_name' => 'referral_bonus',
            //     'category' => 'bonus',
            //     'display_name' => 'Referral Bonus Info',
            //     'description' => 'Menjelaskan apa itu program referral bonus, cara kerjanya, syarat mendapatkannya, dan cara mendapatkan link referral.',
            //     'slug' => 'referral-bonus',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['bonus referral', 'referral bonus', 'apa itu referral', 'cara referral', 'program referral', 'link referral', 'ajak teman dapat bonus', 'referral itu apa', 'cara dapat bonus ajak teman'],
            //     'tool_rules' => "- Jelaskan apa itu program referral bonus secara singkat dan jelas\n- Sebutkan cara mendapatkan link referral\n- Jelaskan syarat-syarat mendapatkan bonus (teman harus deposit)\n- Gunakan tone ramah dan informatif",
            //     'information_text' => [
            //         "Halo Kak! Program referral bonus adalah program di mana Kakak bisa mendapatkan bonus dengan cara mengajak teman untuk bergabung dan bermain. Caranya cukup bagikan link referral Kakak (bisa ditemukan di menu profil/akun), dan ketika teman yang diundang berhasil melakukan deposit, Kakak akan mendapatkan bonus referral secara otomatis 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'referral_bonus_issue',
            //     'category' => 'bonus',
            //     'display_name' => 'Referral Bonus Issue',
            //     'description' => 'Menangani keluhan atau masalah ketika member mengajak teman tetapi bonus referral tidak masuk atau tidak muncul.',
            //     'slug' => 'referral-bonus-issue',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['bonus referral tidak masuk', 'referral tidak masuk', 'bonus tidak ada', 'ajak teman bonus tidak dapat', 'referral tidak dapat bonus', 'teman sudah daftar bonus belum masuk', 'bonus referral hilang', 'bonus ajak teman tidak muncul'],
            //     'tool_rules' => "- Jelaskan bahwa bonus referral memerlukan teman yang diundang sudah melakukan deposit\n- Pastikan teman mendaftar menggunakan link referral milik member\n- Gunakan tone ramah dan membantu",
            //     'information_text' => [
            //         "Halo Kak! Terkait kendala tersebut, biasanya hal ini terjadi karena teman yang Kakak undang belum melakukan deposit, atau mungkin saat mendaftar tidak menggunakan link referral milik Kakak. Boleh tolong dipastikan kembali ke temannya ya, Kak 😊",
            //     ],
            //     'meta' => null,
            // ],
            // [
            //     'tool_name' => 'search_game_guide',
            //     'category' => 'games',
            //     'display_name' => 'Search Game Guide',
            //     'description' => 'Menyediakan panduan ketika member tidak bisa menemukan game tertentu, mengarahkan untuk menggunakan fitur pencarian.',
            //     'slug' => 'search-game-guide',
            //     'type' => 'info',
            //     'is_enabled' => true,
            //     'data_model_id' => null,
            //     'parameters' => null,
            //     'endpoints' => null,
            //     'keywords' => ['game tidak ada', 'game hilang', 'cari game', 'game tidak ditemukan', 'spaceman', 'game kok tidak ada', 'tidak bisa cari game', 'menu pencarian', 'search game', 'game kemana'],
            //     'tool_rules' => "- Arahkan member untuk menggunakan fitur pencarian (ikon kaca pembesar) di website\n- Gunakan tone ramah dan membantu\n- Jangan menyebutkan bahwa game tidak tersedia, arahkan untuk mencari terlebih dahulu",
            //     'information_text' => [
            //         "Halo Kak! Untuk menemukan permainannya dengan cepat, Kakak bisa langsung menuju ke menu pencarian (ikon kaca pembesar) dan mengetikkan nama game yang ingin dimainkan ya 😊",
            //     ],
            //     'meta' => null,
            // ],

            // ─── Deposit tools ───
            [
                'tool_name' => 'checkDeposit',
                'category' => 'payment',
                'display_name' => 'Check Deposit',
                'description' => 'Cek status deposit dan remark pemain berdasarkan username. Menampilkan daftar deposit terbaru dari data model deposit.',
                'slug' => 'check-deposit',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $depositModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek deposit', 'check deposit', 'status deposit', 'deposit status', 'deposit saya', 'deposit belum masuk', 'deposit pending', 'remark deposit'],
                'tool_rules' => "- Check status deposit berdasarkan username\n- Jika username belum ada, minta username secara natural\n- Berikan dan listkan daftar deposit terbaru\n- Tampilkan minimal data operatortime, status, dan remark\n- Urutkan dari deposit terbaru ke yang paling lama\n- Jika tidak ada data deposit, sampaikan dengan jelas bahwa data deposit belum ditemukan",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['created_at', 'status', 'remark'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkWithdraw',
                'category' => 'payment',
                'display_name' => 'Check Withdraw',
                'description' => 'Cek status withdraw dan remark pemain berdasarkan username. Menampilkan daftar withdraw terbaru dari data model withdraw.',
                'slug' => 'check-withdraw',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $withdrawModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek withdraw', 'check withdraw', 'status withdraw', 'withdraw status', 'wd saya', 'withdraw pending', 'remark withdraw'],
                'tool_rules' => "- Check status withdraw berdasarkan username\n- Jika username belum ada, minta username secara natural\n- Berikan dan listkan daftar withdraw terbaru\n- Tampilkan minimal data operatortime, status, dan remark\n- Urutkan dari withdraw terbaru ke yang paling lama\n- Jika tidak ada data withdraw, sampaikan dengan jelas bahwa data withdraw belum ditemukan",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['created_at', 'status', 'remark'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusAPK',
                'category' => 'bonus',
                'display_name' => 'Check Bonus APK',
                'description' => 'Memeriksa status klaim Bonus APK pemain berdasarkan username. Menampilkan daftar bonus APK terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-apk',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusApkModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus apk', 'check bonus apk', 'status bonus apk', 'bonus apk saya', 'bonus apk pending', 'klaim bonus apk'],
                'tool_rules' => "- Periksa status klaim Bonus APK berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus APK terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus APK untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusBeruntun',
                'category' => 'bonus',
                'display_name' => 'Check Bonus Beruntun',
                'description' => 'Memeriksa status klaim Bonus Deposit Beruntun (Daily Streak) pemain berdasarkan username. Menampilkan daftar klaim terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-beruntun',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusBeruntunModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus beruntun', 'check bonus beruntun', 'status bonus beruntun', 'bonus deposit beruntun', 'daily streak bonus'],
                'tool_rules' => "- Periksa status klaim Bonus Deposit Beruntun berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus Beruntun terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus Deposit Beruntun untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusDeposit',
                'category' => 'bonus',
                'display_name' => 'Check Bonus Deposit',
                'description' => 'Memeriksa status klaim Bonus Deposit pemain berdasarkan username. Menampilkan daftar klaim bonus deposit terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-deposit',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusDepositModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus deposit', 'check bonus deposit', 'status bonus deposit', 'bonus deposit saya', 'klaim bonus deposit'],
                'tool_rules' => "- Periksa status klaim Bonus Deposit berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus Deposit terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus Deposit untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusAjakTeman',
                'category' => 'bonus',
                'display_name' => 'Check Bonus Ajak Teman',
                'description' => 'Memeriksa status klaim Bonus Ajak Teman (Referral Bonus) berdasarkan username. Menampilkan daftar klaim terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-ajak-teman',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusAjakTemanModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus ajak teman', 'check bonus ajak teman', 'status bonus referral', 'bonus referral saya', 'klaim bonus referral'],
                'tool_rules' => "- Periksa status klaim Bonus Ajak Teman berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus Ajak Teman terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus Ajak Teman untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusVoucher',
                'category' => 'bonus',
                'display_name' => 'Check Bonus Voucher',
                'description' => 'Memeriksa status klaim Bonus Voucher berdasarkan username. Menampilkan daftar voucher bonus terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-voucher',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusVoucherModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus voucher', 'check bonus voucher', 'status bonus voucher', 'voucher bonus saya', 'klaim bonus voucher'],
                'tool_rules' => "- Periksa status klaim Bonus Voucher berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus Voucher terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus Voucher untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'checkBonusFreespin',
                'category' => 'bonus',
                'display_name' => 'Check Bonus Freespin',
                'description' => 'Memeriksa status klaim Bonus Freespin berdasarkan username. Menampilkan daftar klaim freespin terbaru beserta status dan keterangannya.',
                'slug' => 'check-bonus-freespin',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $bonusFreespinModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'player' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['player'],
                ],
                'endpoints' => null,
                // 'keywords' => ['cek bonus freespin', 'check bonus freespin', 'status bonus freespin', 'freespin saya', 'klaim freespin'],
                'tool_rules' => "- Periksa status klaim Bonus Freespin berdasarkan username pemain\n- Jika username belum tersedia, minta username secara natural\n- Tampilkan daftar klaim Bonus Freespin terbaru milik pemain\n- Sertakan minimal data status, remark, dan keterangan\n- Urutkan dari klaim terbaru ke yang paling lama\n- Jika tidak ada data, sampaikan bahwa belum ada riwayat klaim Bonus Freespin untuk pemain tersebut",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['status', 'remark', 'created_at'],
                        'order_by' => [
                            'field' => 'created_at',
                            'direction' => 'desc',
                        ],
                        'limit' => 1,
                    ],
                ],
            ],
            [
                'tool_name' => 'rejectDeposit',
                'category' => 'payment',
                'display_name' => 'Reject Deposit',
                'description' => 'Menolak deposit pending untuk player. Memerlukan username. Mengirim request ke API endpoint untuk menolak deposit.',
                'slug' => 'reject-deposit',
                'type' => 'update',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username pemain yang depositnya akan ditolak'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => 'https://api-stg.pilartestengine.com/aiservice/api/rejectdeposit',
                        'body' => [
                            'username' => '',
                            'agent' => config('services.agent.kode'),
                        ],
                        'expected_response' => [
                            'status' => 200,
                            'message' => 'Success',
                            'data' => (object) [],
                        ],
                    ],
                ],
                // 'keywords' => ['reject deposit', 'tolak deposit', 'batalkan deposit', 'cancel deposit', 'deposit reject'],
                'tool_rules' => "- Jika username belum ada, minta username terlebih dahulu\n- WAJIB konfirmasi ulang ke user sebelum menjalankan reject deposit — ini adalah aksi sensitif\n- Setelah user mengonfirmasi, baru jalankan tool\n- Jika berhasil, infokan bahwa deposit telah berhasil ditolak dan tampilkan status dari response\n- Jika gagal, infokan error dari response, sarankan mencoba lagi, dan jika masih gagal masalah akan diteruskan ke Human Support",
                'information_text' => null,
                'meta' => null,
            ],
            // ─── LOTTERY / TOGEL tools ───
            [
                'tool_name' => 'checkPoolResult',
                'category' => 'lottery',
                'display_name' => 'Cek Hasil Togel',
                'description' => 'Cek hasil result togel (result1) berdasarkan nama pool. Gunakan pools_id sesuai mapping nama pool.',
                'slug' => 'check-pool-result',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $poolsPeriodeModel?->id,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'pools_id' => [
                            'type' => 'integer',
                            'description' => 'Pool ID: Hongkong=1,Singapore=2,Sydney=3,Samosir=4,HKSiang=5,TotoMacau=6,China=7,Cambodia=8,Oregon1=9,Oregon2=10,Oregon3=11,Oregon4=12,Bullseye=13,Swiss=14,Macau=15,Cairo=16,Taiwan=17,Qatar=18,Malaysia=19,Medan=20. Use integer ID.',
                            'enum' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                        ],
                    ],
                    'required' => ['pools_id'],
                ],
                'endpoints' => null,
                'keywords' => ['hasil togel', 'result togel', 'keluaran togel', 'angka togel', 'nomor togel', 'result pool', 'keluar togel', 'togel hari ini'],
                'tool_rules' => "- SELALU MINTA NAMA POOL TERLEBIH DAHULU SEBELUM DISEBUTKAN\n- Terjemahkan nama pool dari user ke pools_id yang benar sesuai mapping di parameter\n- Tampilkan: tanggal, periode, result1\n- Urutkan dari yang terbaru berdasarkan created_at dan ambil hanya 5 data\n- Jika belum ada result (result1 kosong), infokan bahwa result belum tersedia",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['pools_id', 'date', 'closedt', 'periode', 'result1', 'status'],
                        'order_by' => [
                            'field' => 'closedt',
                            'direction' => 'desc',
                        ],
                        'limit' => 20,
                    ],
                ],
            ],

            // ─── CHANGE REKENING ───────────────────────────────────────────────
            [
                'tool_name'    => 'changeRekening',
                'category'     => 'account',
                'display_name' => 'Ganti Rekening',
                'description'  => 'Permintaan ganti rekening bank player. Memerlukan data rekening lama, rekening baru, dan verifikasi identitas melalui gambar KTP.',
                'slug'         => 'change-rekening',
                'type'         => 'update',
                'is_enabled'   => true,
                'data_model_id' => null,
                'parameters'   => [
                    'type'       => 'object',
                    'properties' => [
                        'namarek'     => ['type' => 'string', 'description' => 'Nama pemilik rekening (Lama)'],
                        'norek'       => ['type' => 'string', 'description' => 'Nomor rekening / Nomor Hp (E-wallet) (Lama)'],
                        'bank'        => ['type' => 'string', 'description' => 'Nama bank / Nama (E-wallet) (Lama)'],
                        'namarek_new' => ['type' => 'string', 'description' => 'Nama rekening (Baru)'],
                        'norek_new'   => ['type' => 'string', 'description' => 'Nomor rekening (Baru)'],
                        'nama_ktp'    => ['type' => 'string', 'description' => 'Kirim Gambar KTP'],
                    ],
                    'required'   => ['namarek', 'norek', 'bank', 'namarek_new', 'norek_new', 'nama_ktp'],
                ],
                'endpoints'    => [
                    'endpoint' => [
                        'route' => 'https://api-stg.pilartestengine.com/aiservice/api/bank/change',
                        'body'  => [
                            'namarek'     => '$arg->namarek',
                            'norek'       => '$arg->norek',
                            'bank'        => '$arg->bank',
                            'namarek_new' => '$arg->namarek_new',
                            'norek_new'   => '$arg->norek_new',
                            'nama_ktp'    => '$arg->nama_ktp',
                            'agent'       => config('services.agent.kode'),
                        ],
                        'expected_response' => [
                            'status'  => 200,
                            'message' => 'Success',
                            'data'    => (object) [],
                        ],
                    ],
                    'chain_rules' => [
                        [
                            'on'         => 'failure',
                            'condition'  => 'equals',
                            'field'      => 'response_status',
                            'value'      => '400',
                            'chain_tool' => 'escalate',
                            'carry_args' => [],
                            'message'    => '',
                        ],
                    ],
                ],
                'keywords'         => null,
                'tool_rules'       => "- Kumpulkan data rekening lama terlebih dahulu: namarek, norek, bank\n- Kumpulkan data rekening baru: namarek_new (nama pemilik rekening baru), norek_new (nomor rekening baru)\n- Setelah data rekening terkumpul, minta user mengirimkan foto KTP yang sesuai dengan nama pemilik rekening baru\n- Analisa gambar dan ekstrak \"Nama\" lengkap yang tertera pada KTP sebagai nilai nama_ktp — nilai ini HANYA boleh diambil dari gambar KTP, JANGAN mengambil dari namarek, namarek_new, atau data lain manapun\n- Jika gambar yang dikirim bukan KTP (tidak terlihat label NIK, Nama, Tempat/Tgl Lahir khas dokumen KTP Indonesia), set nama_ktp = '' dan minta user mengirimkan foto KTP yang benar\n- Jangan eksekusi sebelum semua 6 data lengkap (namarek, norek, bank, namarek_new, norek_new, nama_ktp)\n- Setelah berhasil, konfirmasi kepada user bahwa rekening bank berhasil diperbarui",
                'information_text' => null,
                'meta'             => null,
            ],
        ];

        foreach ($tools as $tool) {
            Tool::query()->updateOrCreate(
                ['tool_name' => $tool['tool_name']],
                $tool
            );
        }

        // Assign all tools to triage agent so it can handle any case
        $triage = \App\Models\ChatAgent::where('agent_type', 'triage')->first();
        if ($triage !== null) {
            $allToolIds = \App\Models\Tool::query()->pluck('id')->toArray();
            $triage->tools()->syncWithoutDetaching($allToolIds);
        }

        // Cleanup deprecated explicit escalate tool.
        Tool::query()->where('tool_name', 'human_support')->delete();
    }
}
