<?php

namespace Database\Seeders;

use App\Models\DataModel;
use App\Models\Tool;
use Illuminate\Database\Seeder;

class ToolSeeder extends Seeder
{
    public function run(): void
    {
        $playersModel = DataModel::query()->where('slug', 'players')->first();
        $playersDataModelId = $playersModel?->id;

        $depositModel = DataModel::query()->where('slug', 'deposit')->first();
        $withdrawModel = DataModel::query()->where('slug', 'withdraw')->first();
        $promoModel = DataModel::query()->where('slug', 'promo')->first();

        $tools = [
            // ─── Internal config (no type) ───
            [
                'tool_name' => '_bot_config',
                'display_name' => 'Bot Config',
                'description' => 'General bot configuration',
                'slug' => '_bot-config',
                'type' => 'info',
                'is_enabled' => false,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => null,
                'tool_rules' => null,
                'information_text' => null,
                'meta' => ['bot_name' => 'xoneBot'],
            ],

            // ─── UPDATE type tools (API endpoint) ───
            [
                'tool_name' => 'resetPassword',
                'display_name' => 'Reset Password',
                'description' => 'Reset user password after account data verification',
                'slug' => 'reset-password',
                'type' => 'update',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username akun'],
                        'namarek' => ['type' => 'string', 'description' => 'Nama rekening'],
                        'norek' => ['type' => 'string', 'description' => 'Nomor rekening'],
                        'bank' => ['type' => 'string', 'description' => 'Nama bank'],
                    ],
                    'required' => ['username', 'namarek', 'norek', 'bank'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => '/resetpassword',
                        'body' => [
                            'username' => '',
                            'namarek' => '',
                            'norek' => '',
                            'bank' => '',
                        ],
                        'expected_response' => [
                            'status' => 200,
                            'message' => 'Success',
                            'data' => (object) [],
                        ],
                    ],
                ],
                'keywords' => ['reset password', 'resetpass', 'kata sandi', 'password'],
                'tool_rules' => "- Minta semua data sekaligus dalam satu pesan yang rapi: username, nama rekening, nomor rekening, nama bank\n- Format permintaan data harus dalam list\n- Jangan eksekusi tool sebelum SEMUA data terkumpul lengkap\n- Setelah berhasil, infokan bahwa password sudah direset ke 1234567\n- Jika data tidak ditemukan, minta user periksa kembali semua data yang diinput",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'register',
                'display_name' => 'Register',
                'description' => 'Register a new player account. Requires username, email, phone number (telepon/hp), bank name, account holder name (nama rekening), and account number (nomor rekening).',
                'slug' => 'register',
                'type' => 'update',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username untuk akun baru'],
                        'email' => ['type' => 'string', 'description' => 'Email untuk akun baru'],
                        'hp' => ['type' => 'string', 'description' => 'Nomor telepon/HP'],
                        'bank' => ['type' => 'string', 'description' => 'Nama bank'],
                        'namarek' => ['type' => 'string', 'description' => 'Nama rekening'],
                        'norek' => ['type' => 'string', 'description' => 'Nomor rekening'],
                    ],
                    'required' => ['username', 'email', 'hp', 'bank', 'namarek', 'norek'],
                ],
                'endpoints' => [
                    'endpoint' => [
                        'route' => '/register',
                        'body' => [
                            'username' => '',
                            'email' => '',
                            'hp' => '',
                            'bank' => '',
                            'namarek' => '',
                            'norek' => '',
                        ],
                        'expected_response' => [
                            'status' => 200,
                            'message' => 'Success',
                            'data' => (object) [],
                        ],
                    ],
                ],
                'keywords' => ['register', 'daftar', 'registrasi', 'buat akun', 'sign up', 'signup', 'mendaftar'],
                'tool_rules' => "- Minta semua data sekaligus dalam satu pesan: username, email, telepon/hp, bank, nama rekening, nomor rekening\n- Validasi format: email harus mengandung @, hp harus numerik, norek harus numerik\n- Jangan eksekusi sebelum semua 6 data lengkap\n- Setelah berhasil registrasi, ucapkan selamat dan berikan panduan login",
                'information_text' => null,
                'meta' => null,
            ],

            // ─── GET type tools (DataModel lookup) ───
            [
                'tool_name' => 'checkSuspend',
                'display_name' => 'Check Suspend',
                'description' => 'Check if a player account is suspended',
                'slug' => 'check-suspend',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $playersDataModelId,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username to check suspend status'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                'keywords' => ['suspend', 'check suspend', 'status', 'suspended', 'cek suspend', 'suspend status'],
                'tool_rules' => "- Minta username terlebih dahulu jika belum diberikan\n- Cek field 'banned_at': jika null berarti TIDAK suspend, jika ada tanggal berarti SUSPEND\n- Jika suspend, infokan bahwa akunnya sedang dalam status suspend dan sarankan hubungi CS via livechat untuk info lebih lanjut\n- Jika tidak suspend, infokan bahwa akun dalam kondisi normal/aktif",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'toStatus',
                'display_name' => 'TurnOver Status',
                'description' => 'Provide information about TurnOver (TO) status for a player. Uses "to" and "targetTo" fields from the Player model.',
                'slug' => 'to-status',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $playersDataModelId,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username untuk cek status TurnOver'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                'keywords' => ['to', 'turnover', 'status to', 'jumlah to', 'target to'],
                'tool_rules' => "- Minta username terlebih dahulu jika belum diberikan\n- Hanya tampilkan informasi field 'to' (jumlah TO saat ini) dan 'targetTo' (target TO yang harus dicapai)\n- Jangan tampilkan field lain dari data player\n- Hitung sisa TO yang harus dicapai: targetTo - to\n- Jika TO sudah mencapai atau melebihi target, infokan bahwa TO sudah terpenuhi dan player bisa melakukan withdraw\n- Jika TO belum tercapai, infokan sisa TO yang harus dipenuhi sebelum bisa withdraw\n- Sarankan player untuk terus bermain agar target TO cepat terpenuhi",
                'information_text' => null,
                'meta' => null,
            ],
            [
                'tool_name' => 'promo',
                'display_name' => 'Promo',
                'description' => 'Provide Promo Information. Retrieves active promotions that are currently running.',
                'slug' => 'promo',
                'type' => 'get',
                'is_enabled' => true,
                'data_model_id' => $promoModel?->id,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['promo', 'list promo', 'daftar promo'],
                'tool_rules' => "- Tampilkan daftar promo yang sedang aktif saat ini\n- Hanya tampilkan field: title, body, category, start_date, end_date, dan buttonlink\n- Jangan tampilkan field internal seperti id, slug, urutan, agent, image, isbanner, ispromotion\n- Presentasikan setiap promo dalam format yang rapi dan menarik\n- Jika ada buttonlink, sertakan link tersebut agar player bisa langsung mengakses promo\n- Jika ada kategori (casino/sports), kelompokkan atau sebutkan kategorinya\n- Jika tidak ada promo aktif, sampaikan bahwa saat ini belum ada promo yang tersedia dan sarankan untuk cek kembali nanti\n- Jangan buat atau karang promo sendiri, hanya tampilkan data yang ada",
                'information_text' => null,
                'meta' => [
                    'query' => [
                        'select' => ['title', 'body', 'category', 'start_date', 'end_date', 'buttonlink'],
                        'filters' => [
                            ['field' => 'status', 'operator' => '=', 'value' => 'active'],
                        ],
                        'date_range' => [
                            'mode' => 'between_now',
                            'start_field' => 'start_date',
                            'end_field' => 'end_date',
                        ],
                        'order_by' => [
                            'field' => 'urutan',
                            'direction' => 'asc',
                        ],
                    ],
                ],
            ],

            // ─── INFO type tools (static information) ───
            [
                'tool_name' => 'game_gacor',
                'display_name' => 'Game Gacor',
                'description' => 'the latest Bocoran Slot Gacor for today. Only take information from the provided list. Do not create new content',
                'slug' => 'game-gacor',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['game gacor', 'slot gacor', 'bocoran slot'],
                'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat konten baru\n- Gunakan emoji dan format menarik untuk presentasi\n- Jika ditanya game yang tidak ada di list, bilang tidak tersedia dan tawarkan yang ada",
                'information_text' => [
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nspadegaming\n-clash of the giants\n-royale vegas\n-brothers kingdom 2\n-gold phanter maxways\n-roma\n\npragmatic play\n-gates of olympus 1000\n-mahjong wins 2 100.000x\n-mahjong wins 3 black scatter\n-sweet bonanza super scatter\n-triple pot gold\n\npgsoft\n-Anubis wrath\n-buffalo win\n-mahjong ways\n-sun & moon\n-cash mania",
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nnolimit city\n- poison Eve\n- The Crypt\n- bounty hunters\n- disturbed\n- dead wood\n\npragmatic play\n- mahjong wins 3 black scatter\n- gates of Olympus 1000\n- gates of gatotkaca 1000\n- starlight princess 1000\n- Aztec gems\n\npgsoft\n- candy burst\n- trasueres of aztec\n- crypto gold\n- emoji riches\n- mafia mayhem",
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nmicrogaming\n- candy rush wilds 2\n- lucky twins wilds\n- 10000 fortunes\n- 777 royal wheel\n- 22 skulls of the dead\n\npragmatic play\n- starlight christmas\n- gates of olympus super scatter\n- sweet bonanza\n- triple pot gold\n- mahjong wins 3 black scatter\n\npgsoft\n- mahjong ways 2\n- wild bounty showdown\n- wild bandito\n- wild ape\n- treasure of Aztec",
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nspadegaming\n- clash of the giants\n- fury max lucky road\n- royale vegas\n- roma\n- sugar party\n\npragmatic play\n- gates of olympus super scatter\n- gates of gatotkaca super scatter\n- pyramid bonanza\n- sweet bonanza\n- sugar rush 1000\n\npgsoft\n- bakery bonanza\n- buffalo win\n- Alibaba's cave of fortune\n- candy bonanza\n- bikini paradise",
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nwonwon\n- olympus 8000\n- mahjong mania\n- zeus\n- ganesha\n- dragon mystery\n\npragmatic play\n- forge of olympus\n- starlight princess 1000\n- pyramid bonanza\n- sweet bonanza\n- wild booster\n\npgsoft\n- mahjong ways\n- buffalo win\n- captain's bounty\n- candy bonanza\n- the great icescape",
                    "🔥🔥bocoran slot hari ini🔥🔥\n#pastiamanpastihoki\n#semogaberuntung\n\nfastspin\n- mahjong princess\n- Caribbean riches\n- golden moon empire\n- jungle quest\n- pai gow ways\n\npragmatic play\n- fortune of olympus\n- gates of Olympus dice\n- sweet bonanza super scatter\n- starlight archer 1000\n- 5 lions megaways\n\npgsoft\n- mahjong ways 2\n- Anubis wrath\n- candy bonanza\n- wild bandito\n- wild bounty showdown",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'pola_gacor',
                'display_name' => 'Pola Gacor',
                'description' => 'the latest Pola Gacor for today. Only take information from the provided list. Do not create new content',
                'slug' => 'pola-gacor',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['pola gacor', 'pola vip', 'pola vvip', 'pola mantap', 'pola terbaik'],
                'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat pola baru\n- Tampilkan pola dengan format asli termasuk emoji ✅❌\n- Jika ditanya game yang tidak ada polanya, bilang belum tersedia",
                'information_text' => "𝐏𝐎𝐋𝐀 𝐕𝐈𝐏  𝐓𝐄𝐑𝐔𝐏𝐃𝐀𝐓𝐄 𝐇𝐀𝐑𝐈 𝐈𝐍𝐈!\nPOLA MAHJONG WAYS 1\nTurbo ✅– MANUAL Spin 10x\nTurbo ✅- AUTO Spin 10x\nTurbo ❌– MANUAL Spin 15x\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400 - 8.000\n\nPOLA WILD BANDITO\nTurbo ✅ – Auto 30\nTurbo ✅ – Manual 18\nTurbo ❌ – Auto 30\nTurbo ✅ – Manual 12\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400\n\nPOLA Mahjong Ways 2\nTurbo ✅– MANUAL Spin 14x\nTurbo ✅- AUTO Spin 30x\nTurbo ❌– MANUAL Spin 10x\n📌𝐑𝐄𝐊𝐎𝐌𝐄𝐍𝐃𝐀𝐒𝐈 𝐁𝐄𝐓: 400 - 8.000\n\n📌𝐏𝐎𝐋𝐀 𝐓𝐄𝐑𝐁𝐀𝐈𝐊 \n📈 𝐆𝐚𝐭𝐞 𝐎𝐟 𝐎𝐥𝐲𝐦𝐩𝐮𝐬 𝟏.𝟎𝟎𝟎⚡️\n-----------------------\n✅❌✅ - 20 AUTO DC ON\n❌✅✅ - 10 MANUAL DC OFF\n❌✅✅ - 30 AUTO DC OFF\n❌❌✅ - 50 MANUAL DC ON\n🔔𝐁𝐔𝐘 𝐒𝐏𝐈𝐍 𝐘𝐀𝐍𝐆 𝐃𝐈𝐒𝐀𝐑𝐀𝐍𝐊𝐀𝐍 𝟐𝟎 𝐑𝐈𝐁𝐔 𝐗5\n🔔𝐁𝐔𝐘 𝐒𝐏𝐈𝐍 𝐘𝐀𝐍𝐆 𝐃𝐈𝐒𝐀𝐑𝐀𝐍𝐊𝐀𝐍 6𝟎 𝐑𝐈𝐁𝐔 𝐗3",
                'meta' => null,
            ],
            [
                'tool_name' => 'bonus',
                'display_name' => 'Bonus',
                'description' => 'detailed information about the bonus claims. Answer any questions members may have regarding how to claim bonuses, eligibility, and any specific conditions or requirements',
                'slug' => 'bonus',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['bonus claim', 'klaim bonus', 'bonus', 'bonus reward'],
                'tool_rules' => "- Infokan cara klaim bonus melalui menu Reward\n- Jika ditanya bonus spesifik, jelaskan bahwa semua bonus bisa diklaim dari menu Reward sebelum bermain\n- Gunakan tone ramah dan semangat",
                'information_text' => ['Halo Kak! Sebelum mulai bermain, jangan lupa untuk melakukan klaim bonusnya terlebih dahulu melalui menu Reward ya'],
                'meta' => null,
            ],
            [
                'tool_name' => 'reward_claim_info',
                'display_name' => 'Reward Claim Info',
                'description' => 'Provide information about why a member cannot claim bonus in the Reward menu, and explain how bonus deposit gratis works after multiple deposits.',
                'slug' => 'reward-claim-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['tidak bisa klaim', 'gagal klaim', 'klaim reward', 'bonus hilang', 'bonus expired', 'bonus deposit gratis', 'reward tidak bisa', 'klaim bonus reward', 'bonus tidak muncul'],
                'tool_rules' => "- Jelaskan bahwa bonus harus diklaim SEBELUM bermain melalui menu Reward\n- Jika tidak diklaim sebelum bermain, bonus akan otomatis expired\n- Jika member sudah terlanjur bermain tanpa klaim, jelaskan bahwa bonus tidak hilang secara permanen\n- Member bisa deposit kembali dan klaim ulang bonus di menu Reward sebelum bermain\n- Gunakan tone ramah dan meyakinkan agar member tidak khawatir",
                'information_text' => [
                    "Klaim bonus harus dilakukan SEBELUM bermain ya Kak. Jika kakak tidak melakukan klaim sebelum bermain, maka bonus akan otomatis expired.",
                    "Tapi tenang Kak, bonus deposit gratis kakak tidak hilang. Jika kakak deposit kembali, kakak bisa klaim ulang bonusnya di menu Reward sebelum bermain. Jadi pastikan selalu klaim bonus dulu sebelum mulai bermain ya Kak! 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'wd_charge_info',
                'display_name' => 'WD Charge Info',
                'description' => 'Provide information about withdrawal (WD) charge. Explains why the amount received does not match the withdrawal amount due to a 2.5% charge when withdrawing more than 5 times per day.',
                'slug' => 'wd-charge-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['wd tidak sesuai', 'withdraw tidak sesuai', 'wd kurang', 'withdraw kurang', 'wd charge', 'potongan wd', 'wd dipotong', 'transfer tidak sesuai', 'nominal wd beda', 'wd terpotong', 'charge wd', 'biaya wd'],
                'tool_rules' => "- Jelaskan bahwa ada charge 2.5% jika melakukan WD lebih dari 5 kali dalam sehari\n- Sampaikan dengan tone ramah dan informatif\n- Sarankan member untuk mengatur jumlah WD agar tidak melebihi 5 kali per hari untuk menghindari charge",
                'information_text' => [
                    "Kakak terkena charge 2,5% ya Kak, karena WD (withdraw) kakak sudah lebih dari 5 kali dalam sehari. Untuk menghindari charge ini, disarankan agar kakak mengatur penarikan tidak lebih dari 5 kali per hari ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'ewallet_premium_info',
                'display_name' => 'E-Wallet Premium Info',
                'description' => 'Provide information that E-Wallet accounts must be Premium status for registration and transactions on the platform.',
                'slug' => 'ewallet-premium-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['ewallet', 'e-wallet', 'ewallet premium', 'rek ewallet', 'dompet digital', 'ovo', 'dana', 'gopay', 'shopeepay', 'linkaja', 'wajib premium', 'premium ewallet', 'upgrade ewallet'],
                'tool_rules' => "- Jelaskan bahwa semua akun E-Wallet WAJIB berstatus Premium\n- Sarankan member untuk upgrade E-Wallet terlebih dahulu sebelum mendaftar atau melakukan transaksi\n- Gunakan tone ramah dan informatif",
                'information_text' => [
                    "Halo Kak, untuk penggunaan E-Wallet di situs kami, semua akun diwajibkan sudah berstatus Premium. Silakan pastikan E-Wallet Kakak sudah di-upgrade sebelum melakukan pendaftaran atau transaksi ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'situs_partner_info',
                'display_name' => 'Situs Partner Info',
                'description' => 'Provide information that partner sites are only partners and not part of the same company.',
                'slug' => 'situs-partner-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['situs partner', 'partner', 'satu company', 'satu perusahaan', 'afiliasi', 'hubungan situs', 'situs lain', 'sister site'],
                'tool_rules' => "- Jelaskan bahwa situs partner hanya sebagai partner saja, bukan satu company\n- Jangan memberikan informasi lebih lanjut mengenai detail internal perusahaan\n- Gunakan tone ramah dan singkat",
                'information_text' => [
                    "Hanya sebagai situs partner saja ya Kak, bukan satu company 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_lose_info',
                'display_name' => 'Parlay Lose Info',
                'description' => 'Provide information about what happens when one match in a Mix Parlay ticket loses.',
                'slug' => 'parlay-lose-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['parlay kalah', 'mix parlay', 'parlay lose', 'tiket parlay', 'parlay gugur', 'parlay kalah satu', 'parlay salah satu kalah'],
                'tool_rules' => "- Jelaskan bahwa jika satu pertandingan saja kalah (Lose), seluruh tiket Mix Parlay gugur/kalah total\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Jika ada satu saja pertandingan yang tebakannya salah atau kalah penuh (Lose), maka seluruh tiket Mix Parlay tersebut dinyatakan gugur atau kalah total ya Kak.",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_draw_info',
                'display_name' => 'Parlay Draw Info',
                'description' => 'Provide information about what happens when a match in a Mix Parlay ticket results in a Draw.',
                'slug' => 'parlay-draw-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['parlay seri', 'parlay draw', 'pertandingan seri', 'parlay hasil seri', 'odds draw', 'draw parlay'],
                'tool_rules' => "- Jelaskan bahwa pertandingan seri (Draw) tidak membuat tiket gugur\n- Odds pertandingan seri diubah menjadi 1 (tidak mempengaruhi perkalian)\n- Tiket tetap berjalan dengan sisa pertandingan lainnya\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Jika tebakan hasilnya seri (dan tidak ada sistem handicap yang memenangkan salah satu pihak), maka status pertandingan tersebut dianggap Draw. Nilai odds untuk pertandingan yang seri akan diubah menjadi 1 (tidak mempengaruhi perkalian), dan tiket tetap berjalan dengan sisa pertandingan lainnya ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_won_half_info',
                'display_name' => 'Parlay Won Half Info',
                'description' => 'Provide information about Won Half (Menang Setengah) status in Mix Parlay and how it affects odds calculation.',
                'slug' => 'parlay-won-half-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['menang setengah', 'won half', 'parlay menang setengah', 'half win', 'parlay half', 'setengah menang', 'menang setengah parlay', 'hitung odds menang setengah', 'rumus won half', 'perhitungan odds half'],
                'tool_rules' => "- Jelaskan konsep Menang Setengah (Won Half) dalam konteks Parlay\n- Jelaskan bahwa tiket tetap hidup tetapi odds dihitung ulang dengan rumus khusus\n- Jelaskan rumus perhitungan odds: (Odds awal - 1) / 2 + 1\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Menang Setengah (Won Half) terjadi jika tim yang dipilih menang berdasarkan sistem handicap (voor), tetapi selisih golnya hanya mencapai setengah dari nilai handicap tersebut. Tiket tetap hidup ya Kak, tetapi nilai odds tim tersebut akan dihitung ulang dengan rumus khusus sebelum dikalikan dengan tim lain 😊",
                    "Rumus untuk menghitung odds Menang Setengah: (Nilai Odds awal - 1) dibagi 2, kemudian ditambah 1. Hasil angka ini yang akan dikalikan dengan odds pertandingan lainnya ya Kak.",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_odds_calculation',
                'display_name' => 'Parlay Odds Calculation',
                'description' => 'Provide information about how to calculate total odds in Mix Parlay by multiplying all selected match odds together.',
                'slug' => 'parlay-odds-calculation',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['hitung odds parlay', 'total odds', 'kalkulasi parlay', 'cara hitung parlay', 'odds parlay', 'perhitungan parlay', 'rumus parlay', 'hitung mix parlay'],
                'tool_rules' => "- Jelaskan bahwa total odds dihitung dengan mengalikan semua odds pertandingan yang dipilih\n- Berikan contoh perhitungan jika diperlukan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Total odds dalam Mix Parlay dihitung dengan mengalikan semua odds dari pertandingan yang Kakak pilih. Misalnya, jika Kakak memilih 3 tim dengan odds 1.80, 2.00, dan 1.50, maka total odds adalah: 1.80 x 2.00 x 1.50 = 5.40 ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_payout_calculation',
                'display_name' => 'Parlay Payout Calculation',
                'description' => 'Provide information about how to calculate total winnings or payout in Mix Parlay.',
                'slug' => 'parlay-payout-calculation',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['payout parlay', 'kemenangan parlay', 'hitung kemenangan', 'total kemenangan', 'keuntungan parlay', 'profit parlay', 'hitung payout', 'hasil parlay'],
                'tool_rules' => "- Jelaskan rumus: total odds x modal taruhan = total payout, lalu kurangi modal untuk keuntungan bersih\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Total kemenangan dihitung dengan mengalikan total odds dengan nominal modal taruhan Kakak, kemudian dikurangi dengan modal awal tersebut jika ingin melihat keuntungan bersih ya Kak. Contoh: total odds 5.40 x modal 100rb = 540rb (payout), keuntungan bersih = 540rb - 100rb = 440rb 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'parlay_void_postponed_info',
                'display_name' => 'Parlay Void / Postponed Info',
                'description' => 'Provide information about what happens when a match in Mix Parlay is cancelled, postponed, or voided.',
                'slug' => 'parlay-void-postponed-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['parlay batal', 'pertandingan batal', 'postponed', 'parlay void', 'match batal', 'pertandingan ditunda', 'parlay ditunda', 'void parlay'],
                'tool_rules' => "- Jelaskan bahwa pertandingan yang batal/ditunda akan dianggap Void\n- Odds pertandingan Void diubah menjadi 1 (tidak mempengaruhi tiket)\n- Sisa tiket tetap berjalan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Jika pertandingan dibatalkan atau ditunda melewati batas waktu tertentu (biasanya 24 jam), pertandingan tersebut akan dianggap batal (Void). Nilai odds untuk pertandingan itu akan diubah menjadi 1, sehingga tidak mempengaruhi status menang/kalah dari sisa tiket Parlay Kakak ya 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'handicap_info',
                'display_name' => 'Handicap (HDP) Info',
                'description' => 'Provide information about HDP or Asian Handicap system in sports betting, explaining how voor (goal advantage/disadvantage) works.',
                'slug' => 'handicap-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['hdp', 'handicap', 'asian handicap', 'voor', 'voor gol', 'apa itu hdp', 'apa itu handicap', 'sistem voor'],
                'tool_rules' => "- Jelaskan konsep HDP / Asian Handicap secara sederhana\n- Jelaskan bahwa tim kuat memberi voor ke tim lemah untuk menyeimbangkan peluang\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "HDP atau Asian Handicap adalah sistem pemberian nilai tambah atau kurang (voor) berupa gol kepada salah satu tim. Tim yang lebih kuat biasanya akan memberikan voor kepada tim yang lebih lemah untuk menyeimbangkan peluang ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'over_under_info',
                'display_name' => 'Over/Under (O/U) Info',
                'description' => 'Provide information about Over/Under (O/U) betting type, explaining how total goals prediction works.',
                'slug' => 'over-under-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['over under', 'o/u', 'over/under', 'atas bawah', 'total gol', 'apa itu over under', 'apa itu o/u', 'ou'],
                'tool_rules' => "- Jelaskan konsep Over/Under secara sederhana\n- Jelaskan bahwa pemain menebak total gol di atas atau di bawah batas yang ditentukan\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Over/Under (Atas/Bawah) adalah jenis taruhan di mana pemain menebak total gol yang tercipta dalam suatu pertandingan, apakah berada di atas (Over) atau di bawah (Under) batas angka yang telah ditentukan ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => '1x2_info',
                'display_name' => '1x2 Info',
                'description' => 'Provide information about the 1x2 betting format, explaining Home win, Draw, and Away win.',
                'slug' => '1x2-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['1x2', 'apa itu 1x2', 'taruhan 1x2', 'home draw away', '1 x 2', 'format 1x2'],
                'tool_rules' => "- Jelaskan format taruhan 1x2 secara sederhana\n- Jelaskan arti 1 (Home), X (Draw), 2 (Away)\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "1x2 adalah format taruhan klasik tanpa handicap ya Kak. Angka \"1\" mewakili kemenangan tuan rumah (Home), \"X\" mewakili hasil seri (Draw), dan \"2\" mewakili kemenangan tim tamu (Away) 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'odd_even_info',
                'display_name' => 'Odd/Even (O/E) Info',
                'description' => 'Provide information about Odd/Even (O/E) betting type, explaining how to predict whether total goals will be odd or even.',
                'slug' => 'odd-even-info',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['odd even', 'o/e', 'odd/even', 'ganjil genap', 'apa itu odd even', 'apa itu o/e', 'taruhan ganjil genap'],
                'tool_rules' => "- Jelaskan konsep Odd/Even secara sederhana\n- Jelaskan bahwa pemain menebak total gol ganjil atau genap\n- Gunakan tone informatif dan jelas\n- Jangan memberikan tips atau saran taruhan",
                'information_text' => [
                    "Odd/Even (Ganjil/Genap) adalah taruhan yang menebak apakah total keseluruhan gol dari kedua tim yang bertanding pada akhir laga akan bernilai ganjil atau genap ya Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'link_rtp',
                'display_name' => 'Link RTP',
                'description' => 'Provide information about RTP links for online slots or games. Answer any questions regarding how RTP is calculated, where to find RTP links, and how it affects gameplay or chances of winning.',
                'slug' => 'link-rtp',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['link rtp', 'rtp', 'link anti rungkat'],
                'tool_rules' => "- Berikan link RTP dari information text\n- Jelaskan bahwa link tersebut menampilkan winrate game tertinggi secara realtime\n- Jangan buat atau tebak link sendiri",
                'information_text' => ["klik link untuk cek rtp kami disini dengan winrate game tertinggi kak 🙂\n- realtime - akurat - anti rungkat -\n\nhttps://rtpbigmsg77.xyz\n\ndan sudah tersedia jadwal dan pola gacor nya kak"],
                'meta' => null,
            ],
            [
                'tool_name' => 'link_apk',
                'display_name' => 'Link APK',
                'description' => 'Provide a link to download the APK for the specified app. Ensure the link is from a trusted source to guarantee security.',
                'slug' => 'link-apk',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['link apk', 'download apk', 'apk', 'url apk'],
                'tool_rules' => "- Berikan link APK dari information text\n- Jangan buat atau tebak link sendiri, gunakan HANYA link yang tersedia\n- Ajak user untuk mendaftar atau bermain dengan nada ramah dan semangat",
                'information_text' => ["silahkan akses link apk untuk daftar ataupun bermain di bigmsg ya kak\n\nhttps://apk.hi11office.com/BIGMSG(2.0.6).apk\n\nselamat bermain dan semoga beruntung"],
                'meta' => null,
            ],
            [
                'tool_name' => 'depositPulsa',
                'display_name' => 'Deposit Pulsa',
                'description' => 'Provide step-by-step instructions on how to make a deposit via mobile phone credit (pulsa). Covers XL and Telkomsel top-up process through the website deposit form.',
                'slug' => 'deposit-pulsa',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['deposit pulsa', 'pulsa'],
                'tool_rules' => "- Jawab HANYA dari information text yang tersedia, jangan buat panduan sendiri\n- Jelaskan langkah-langkah dengan format yang rapi dan mudah dipahami\n- Tekankan bahwa player harus mencantumkan SN atau nomor pengirim di kolom keterangan\n- Jika ditanya metode deposit lain selain pulsa, arahkan untuk menghubungi CS atau cek menu deposit di website",
                'information_text' => ["Cara depo melalui pulsa:\nKakak buka website kami, lalu ke menu form deposit. Setelah itu kakak pilih tujuan pulsa XL atau Telkomsel. Setelah itu kakak isi pulsa ke nomor tersebut, dan setelah sukses, kakak isi form deposit nya sesuai dengan nominal pulsa yang kakak isi. Jangan lupa di kolom keterangan kakak isi/cantumkan SN nya atau nomor pengirim (jika transfer pulsa), lalu ajukan form deposit nya."],
                'meta' => null,
            ],

            // ─── GET MULTIPLE type tools ───
            [
                'tool_name' => 'BonusCashback',
                'display_name' => 'Bonus Cashback',
                'description' => 'Provide information about bonus cashback. Compare total "amount" on Deposit and Withdraw model in LAST WEEK where status is "accept". If total Withdraw amount > total Deposit amount, the player has no cashback.',
                'slug' => 'bonus-cashback',
                'type' => 'get_multiple',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => [
                    'type' => 'object',
                    'properties' => [
                        'username' => ['type' => 'string', 'description' => 'Username pemain'],
                    ],
                    'required' => ['username'],
                ],
                'endpoints' => null,
                'keywords' => ['cashback', 'bonus cashback', 'cek cashback'],
                'tool_rules' => "- Minta username terlebih dahulu jika belum diberikan\n- Bandingkan total amount dari Deposit dan Withdraw minggu lalu (Senin-Minggu) dengan status \"accept\"\n- Periode minggu lalu = Senin 00:00:00 sampai Minggu 23:59:59 dari minggu sebelumnya\n- Jika total Withdraw > total Deposit, berarti pemain TIDAK mendapatkan cashback (sudah profit/menang)\n- Jika total Deposit > total Withdraw, pemain BERHAK mendapatkan cashback dari selisihnya\n- Jika tidak ada data deposit atau withdraw, sampaikan bahwa tidak ada transaksi di minggu lalu\n- Tampilkan: total deposit, total withdraw, selisih, dan status kelayakan cashback\n- Format angka dalam mata uang (gunakan separator ribuan)\n- Jangan simpulkan rate/persentase cashback, hanya sampaikan data perbandingan dan kelayakan",
                'information_text' => null,
                'meta' => [
                    'data_model_ids' => array_filter([
                        $depositModel?->id,
                        $withdrawModel?->id,
                    ]),
                    'query' => [
                        'filters' => [
                            ['field' => 'status', 'operator' => '=', 'value' => 'accept'],
                        ],
                        'date_range' => [
                            'field' => 'date',
                            'range' => 'last_week',
                        ],
                        'aggregate' => [
                            'function' => 'sum',
                            'field' => 'amount',
                        ],
                        'order_by' => [
                            'field' => 'id',
                            'direction' => 'desc',
                        ],
                    ],
                ],
            ],
            [
                'tool_name' => 'referral_bonus_issue',
                'display_name' => 'Referral Bonus Issue',
                'description' => 'Provide information when a member asks about referral bonus not appearing after inviting a friend.',
                'slug' => 'referral-bonus-issue',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['bonus referral', 'ajak teman', 'bonus tidak ada', 'referral tidak masuk', 'undang teman', 'bonus ajak teman', 'referral bonus', 'link referral'],
                'tool_rules' => "- Jelaskan bahwa bonus referral memerlukan teman yang diundang sudah melakukan deposit\n- Pastikan teman mendaftar menggunakan link referral milik member\n- Gunakan tone ramah dan membantu",
                'information_text' => [
                    "Halo Kak! Terkait kendala tersebut, biasanya hal ini terjadi karena teman yang Kakak undang belum melakukan deposit, atau mungkin saat mendaftar tidak menggunakan link referral milik Kakak. Boleh tolong dipastikan kembali ke temannya ya, Kak 😊",
                ],
                'meta' => null,
            ],
            [
                'tool_name' => 'search_game_guide',
                'display_name' => 'Search Game Guide',
                'description' => 'Provide guidance when a member cannot find a specific game, directing them to use the search feature.',
                'slug' => 'search-game-guide',
                'type' => 'info',
                'is_enabled' => true,
                'data_model_id' => null,
                'parameters' => null,
                'endpoints' => null,
                'keywords' => ['game tidak ada', 'game hilang', 'cari game', 'game tidak ditemukan', 'spaceman', 'game kok tidak ada', 'tidak bisa cari game', 'menu pencarian', 'search game', 'game kemana'],
                'tool_rules' => "- Arahkan member untuk menggunakan fitur pencarian (ikon kaca pembesar) di website\n- Gunakan tone ramah dan membantu\n- Jangan menyebutkan bahwa game tidak tersedia, arahkan untuk mencari terlebih dahulu",
                'information_text' => [
                    "Halo Kak! Untuk menemukan permainannya dengan cepat, Kakak bisa langsung menuju ke menu pencarian (ikon kaca pembesar) dan mengetikkan nama game yang ingin dimainkan ya 😊",
                ],
                'meta' => null,
            ],
        ];

        foreach ($tools as $tool) {
            Tool::query()->updateOrCreate(
                ['tool_name' => $tool['tool_name']],
                $tool
            );
        }
    }
}
